

CREATE or replace TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_PERSON_STG_CF (
	PSN_REC_KEY BIGINT, -- REPRESENT POINTER BACK TO PERSON DIM
	SOURCEHASH1 VARBINARY(32),  -- TYPE1 SOURCE HASHING
	SOURCEHASH2 VARCHAR(32),	-- TYPE2 SOURCE HASHING
	ISTYPE1	INT,  -- REPRESENTS TYPE 1
	ISTYPE2 INT,  -- REPRESENTS TYPE 2
	ISNEW INT, -- INDICATION FOR NEW RECORD
	SERIAL NUMBER(19,0),  -- NATURAL KEY
	HOUSEHOLD_PERSON_SERIAL NUMBER(19,0),	
	NAICS_SERIAL NUMBER(19,0),
	RELATIONSHIP_SERIAL NUMBER(19,0),
	TAX_PERSON_SERIAL NUMBER(19,0),
	TAX_STATE_SERIAL NUMBER(19,0),
	TYPE_SERIAL NUMBER(19,0),
	TIN VARCHAR(9),
	ACCESS_RESTRICTION VARCHAR(1),
	BACKUP_WITHHOLD VARCHAR(1),
	BIRTH_DATE DATE,
	CATEGORY VARCHAR(1),
	CHECK_HOLD_LEVEL_SERIAL NUMBER(19,0),
	CTR_EXEMPTION VARCHAR(1),
	CTR_EXEMPTION_REVIEW_DATE DATE,
	DEATH_DATE DATE,
	DEMOGRAPHICS_FURNISHED VARCHAR(1),
	TITLE VARCHAR(10),
	FIRST_NAME VARCHAR(20),
	MIDDLE_NAME VARCHAR(20),
	LAST_NAME VARCHAR(80),
	NICKNAME VARCHAR(20),
	SUFFIX VARCHAR(10),
	GENDER VARCHAR(1),
	HOUSEHOLD_CATEGORY VARCHAR(1),
	HOUSEHOLD_REASSIGNMENT VARCHAR(1),
	IRS_FORM_W8_EXPIRATION_DATE DATE,
	IRS_FORM_W9_RECEIVED_DATE DATE,
	MARKETING_OPTION VARCHAR(2),
	NOTE_RESTRICTION VARCHAR(1),
	OFAC_LAST_CHECK_DATE DATE,
	OFAC_RESTRICTION VARCHAR(1),
	OWNERSHIP_CHANGE_DATE DATE,
	RELATIONSHIP_OVR_EFF_DATE DATE,
	RELATIONSHIP_OVR_EXP_DATE DATE,
	RELATIONSHIP_OVR_SERIAL NUMBER(19,0),
	ROW_CHANGE_TIMESTAMP TIMESTAMP_NTZ(9),
	TAX_COUNTRY_CODE VARCHAR(2),
	TAX_REPORTING VARCHAR(1),
	LAST_FM_DATE DATE,
	PRIMARY KEY (SERIAL)
);


--ALTER TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_PERSON_STG_CF CLUSTER BY (SOURCEHASH2);

create or replace TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_ACCOUNT_STG_CF (
	ACCT_REC_KEY BIGINT, -- REPRESENT POINTER BACK TO ACCOUNT DIM
	SOURCEHASH1 VARCHAR(32),  -- TYPE1 SOURCE HASHING
	SOURCEHASH2 VARCHAR(32),	-- TYPE2 SOURCE HASHING
	ISTYPE1	INT,  -- REPRESENTS TYPE 1
	ISTYPE2 INT,  -- REPRESENTS TYPE 2
	ISNEW INT, -- INDICATION FOR NEW RECORD	
	SERIAL NUMBER(19,0), -- NATURAL KEY
	STORED_ACCESS_KEY VARCHAR(200),
	LAST_FM_DATE DATE,
	ACCOUNT_NUMBER VARCHAR(10),
	ACCOUNT_TITLE VARCHAR(120),
	PRIMARY_PERSON_SERIAL NUMBER(19,0),
	OPEN_DATE DATE,
	OPENED_BY_USER_SERIAL NUMBER(19,0),
	CLOSE_DATE DATE,
	CLOSE_REASON_SERIAL NUMBER(19,0),
	CORRESPONDENCE_DATE DATE,
	TYPE_SERIAL NUMBER(19,0),
	MAIL_PERSON_ADDR_LINK_SERIAL NUMBER(19,0),
	E_NOTICE_OPTION VARCHAR(1),
	E_STMT_OPTION VARCHAR(1),
	E_STMT_NOTIFICATION VARCHAR(1),
	E_STMT_PERSON_CONTACT_SERIAL NUMBER(19,0),
	STMT_CUTOFF_CYCLE_SERIAL NUMBER(19,0),
	STMT_CUTOFF_CYCLE_OPTION VARCHAR(1),
	RELATIONSHIP_SERIAL NUMBER(19,0),
	RELATIONSHIP_OVR_SERIAL NUMBER(19,0),
	RELATIONSHIP_OVR_EFF_DATE DATE,
	RELATIONSHIP_OVR_EXP_DATE DATE,
	ELIGIBILITY_SERIAL NUMBER(19,0),
	SHARED_BRANCH_OPTION VARCHAR(1),
	BILL_PAYMENT_OPTION VARCHAR(1),
	ACCESS_RESTRICTION VARCHAR(1),
	NOTE_RESTRICTION VARCHAR(1),
	DELINQUENCY_RESTRICTION VARCHAR(1),
	DELINQUENCY_R_EXEMPT_EXP_DATE DATE,
	NEW_ACT_ALERT_EXPIRATION_DATE DATE,
	CK_HLD_NEW_ACT_EXPIRATION_DATE DATE,
	CK_HLD_REP_OVR_EXPIRATION_DATE DATE,
	CK_HLD_SPC_CSE_OPTION VARCHAR(1),
	CK_HLD_SPC_CSE_REASON VARCHAR(40),
	CK_HLD_SPC_CSE_EXPIRATION_DATE DATE,
	ROW_CHANGE_TIMESTAMP TIMESTAMP_NTZ(9),
	CHECK_HOLD_LEVEL_SERIAL NUMBER(19,0),
	DORMANCY_RESTRICTION VARCHAR(1),
	PRIMARY KEY (SERIAL)
);


create or replace TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_ACCOUNT_ELIGIBILITY_STG_CF (
	ELIG_REC_KEY BIGINT,-- REPRESENT POINTER BACK TO ACCOUNT_ELIGIBILITY DIM
	SOURCEHASH1 VARCHAR(32),  -- TYPE1 SOURCE HASHING
	SOURCEHASH2 VARCHAR(32),	-- TYPE2 SOURCE HASHING
	ISTYPE1	INT,  -- REPRESENTS TYPE 1
	ISTYPE2 INT,  -- REPRESENTS TYPE 2
	ISNEW INT, -- INDICATION FOR NEW RECORD		
	SERIAL NUMBER(19,0),--NATURAL Key
	LAST_FM_DATE DATE,
	DESCRIPTION VARCHAR(40),
	STATUS VARCHAR(1),
	CODE VARCHAR(40),
	PRIMARY KEY (SERIAL)
);

create or replace TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_ACCOUNT_CLOSE_REASON_STG_CF (
	CLRSN_REC_KEY BIGINT,-- REPRESENT POINTER BACK TO ACCOUNT_CLOSE_REASON DIM
	SOURCEHASH1 VARCHAR(32),  -- TYPE1 SOURCE HASHING
	SOURCEHASH2 VARCHAR(32),	-- TYPE2 SOURCE HASHING
	ISTYPE1	INT,  -- REPRESENTS TYPE 1
	ISTYPE2 INT,  -- REPRESENTS TYPE 2
	ISNEW INT, -- INDICATION FOR NEW RECORD			
	SERIAL NUMBER(19,0),--NATURAL KEY
	LAST_FM_DATE DATE,
	DESCRIPTION VARCHAR(40),
	STATUS VARCHAR(1),
	CODE VARCHAR(40),
	PRIMARY KEY (SERIAL)
);

create or replace TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_USER_STG_CF (
	USER_REC_KEY BIGINT,-- REPRESENT POINTER BACK TO ACCOUNT_CLOSE_REASON DIM
	SOURCEHASH1 VARCHAR(32),  -- TYPE1 SOURCE HASHING
	SOURCEHASH2 VARCHAR(32),	-- TYPE2 SOURCE HASHING
	ISTYPE1	INT,  -- REPRESENTS TYPE 1
	ISTYPE2 INT,  -- REPRESENTS TYPE 2
	ISNEW INT, -- INDICATION FOR NEW RECORD	
	SERIAL NUMBER(19,0), -- NATURAL KEY
	LAST_FM_DATE DATE,
	USERNAME VARCHAR(40),
	DOMAIN_NAME VARCHAR(40),
	CATEGORY VARCHAR(1),
	RECEIPT_ID VARCHAR(20),
	AIRES_CODE VARCHAR(3),
	PERSON_SERIAL NUMBER(19,0),
	LAST_LOGIN_TIME TIMESTAMP_NTZ(9),
	UNSUCCESSFUL_LOGIN_TIME TIMESTAMP_NTZ(9),
	UNSUCCESSFUL_LOGIN_COUNT NUMBER(5,0),
	LOGIN_LOCK VARCHAR(1),
	LOGIN_CHANNEL_SERIAL NUMBER(19,0),
	ROLE_SERIAL NUMBER(19,0),
	TEST_ROLE_SERIAL NUMBER(19,0),
	SEC_OVR_REQ_NOT_GROUP_SERIAL NUMBER(19,0),
	SEC_OVR_GRANTOR_GROUP_SERIAL NUMBER(19,0),
	SEC_OVR_GRANTOR_NOT_ADDRESSES VARCHAR(200),
	WARNING_HANDLING VARCHAR(1),
	HIRE_DATE DATE,
	TERMINATION_DATE DATE,
	JOB_TITLE VARCHAR(40),
	DEPARTMENT_SERIAL NUMBER(19,0),
	MANAGER_USER_SERIAL NUMBER(19,0),
	PHONE_NUMBER VARCHAR(40),
	FAX_NUMBER VARCHAR(40),
	EMAIL_ADDRESS VARCHAR(80),
	BRANCH_SERIAL NUMBER(19,0),
	NMLSR_ID VARCHAR(12),
	OUT_OF_OFFICE_MESSAGE VARCHAR(80),
	OUT_OF_OFFICE_RETURN_TIME TIMESTAMP_NTZ(9),
	PROFILE_IMAGE VARCHAR(2097152),
	PROFILE_IMAGE_FORMAT VARCHAR(4),
	PROFILE_IMAGE_MOD_TIME TIMESTAMP_NTZ(9),
	SIGNATURE_IMAGE VARCHAR(2097152),
	SIGNATURE_IMAGE_FORMAT VARCHAR(4),
	SIGNATURE_IMAGE_MOD_TIME TIMESTAMP_NTZ(9),
	EX_CREDIT_PULL_USER_SERIAL NUMBER(19,0),
	TU_CREDIT_PULL_USER_SERIAL NUMBER(19,0),
	EQ_CREDIT_PULL_USER_SERIAL NUMBER(19,0),
	CS_CREDIT_PULL_USER_SERIAL NUMBER(19,0),
	CS_LOCATION_ID VARCHAR(30),
	SHARED_BRANCH_TELLER_ID VARCHAR(8),
	SALES_OPPORTUNITY_OPTION VARCHAR(2),
	PERSON_VERIFICATION_OPTION VARCHAR(1),
	PROF_ACCESS_INT_TY_SPECIFY VARCHAR(1),
	PROF_ACCESS_INT_TY_SERIAL NUMBER(19,0),
	AD_HOC_REP_USERNAME VARCHAR(40),
	AD_HOC_REP_PASSWORD VARCHAR(56),
	AD_HOC_REP_DASHBOARD_NAME VARCHAR(200),
	ACCESS_LOGGING VARCHAR(1),
	SERVER_USERNAME VARCHAR(8),
	SERVER_PASSWORD VARCHAR(56),
	USER_INTERFACE_SETTINGS VARCHAR(16777216),
	AD_HOC_REP_ROLE_LIST VARCHAR(200),
	NMLSR_STATE VARCHAR(2),
	NMLSR_EFFECTIVE_DATE DATE,
	NMLSR_EXPIRATION_DATE DATE,
	PERSON_INFO_CHANGE_HISTORY VARCHAR(1),
	PRIMARY KEY (SERIAL)
);

create or replace TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_AC_NOTE_STG_CF (
	ACNOTE_REC_KEY BIGINT,-- REPRESENT POINTER BACK TO DIM
	SOURCEHASH1 VARCHAR(32),  -- TYPE1 SOURCE HASHING
	SOURCEHASH2 VARCHAR(32),	-- TYPE2 SOURCE HASHING
	ISTYPE1	INT,  -- REPRESENTS TYPE 1
	ISTYPE2 INT,  -- REPRESENTS TYPE 2
	ISNEW INT, -- INDICATION FOR NEW RECORD	
	SERIAL NUMBER(19,0), -- NATURAL KEY
	PARENT_SERIAL NUMBER(19,0),
	ORDINAL NUMBER(19,0),
	LAST_FM_DATE DATE,
	TYPE_SERIAL NUMBER(19,0),
	PLACEMENT_DATE DATE,
	PLACEMENT_TIME TIMESTAMP_NTZ(9),
	PLACEMENT_USER_SERIAL NUMBER(19,0),
	EXPIRATION_DATE DATE,
	EXPLANATION VARCHAR(2000),
	PRIMARY KEY (SERIAL)
);

-- RRCU_STG_DEV.KEYSTONE_CORE.T_KS_PERSON_ADDRESS_LINK_STG definition

create or replace TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_PERSON_ADDRESS_LINK_STG_CF (
	PSNADDR_REC_KEY BIGINT,-- REPRESENT POINTER BACK TO DIM
	SOURCEHASH1 VARCHAR(32),  -- TYPE1 SOURCE HASHING
	SOURCEHASH2 VARCHAR(32),	-- TYPE2 SOURCE HASHING
	ISTYPE1	INT,  -- REPRESENTS TYPE 1
	ISTYPE2 INT,  -- REPRESENTS TYPE 2
	ISNEW INT, -- INDICATION FOR NEW RECORD	
	SERIAL NUMBER(19,0),
	PARENT_SERIAL NUMBER(19,0),
	ORDINAL NUMBER(19,0),
	LAST_FM_DATE DATE,
	ADDRESS_SERIAL NUMBER(19,0),
	CATEGORY VARCHAR(1),
	BAD_ADDRESS VARCHAR(1),
	TYPE_SERIAL NUMBER(19,0),
	EFFECTIVE_DATE DATE,
	EXPIRATION_DATE DATE,
	SEASON_START_MONTH NUMBER(5,0),
	SEASON_START_DAY NUMBER(5,0),
	SEASON_END_MONTH NUMBER(5,0),
	SEASON_END_DAY NUMBER(5,0),
	CRED_REP_ADDRESS_INDICATOR VARCHAR(1),
	CRED_REP_RESIDENCE_CODE VARCHAR(1),
	LAST_VERIFICATION_DATE DATE,
	OWN_RENT VARCHAR(1),
	PRIMARY KEY (SERIAL)
);

-- RRCU_STG_DEV.KEYSTONE_CORE.T_KS_PERSON_CONTACT_STG definition

create or replace TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_PERSON_CONTACT_STG_CF (
	PSNCONT_REC_KEY BIGINT,-- REPRESENT POINTER BACK TO DIM
	SOURCEHASH1 VARCHAR(32),  -- TYPE1 SOURCE HASHING
	SOURCEHASH2 VARCHAR(32),	-- TYPE2 SOURCE HASHING
	ISTYPE1	INT,  -- REPRESENTS TYPE 1
	ISTYPE2 INT,  -- REPRESENTS TYPE 2
	ISNEW INT, -- INDICATION FOR NEW RECORD	
	SERIAL NUMBER(19,0),
	PARENT_SERIAL NUMBER(19,0),
	ORDINAL NUMBER(19,0),
	LAST_FM_DATE DATE,
	CATEGORY VARCHAR(2),
	DESCRIPTION VARCHAR(40),
	VALUE VARCHAR(80),
	MARKETING_OPTION VARCHAR(1),
	CARD_FRAUD_ALERT_OPTION VARCHAR(1),
	ALERT_OPTION VARCHAR(1),
	BAD_CONTACT VARCHAR(1),
	EXPIRATION_DATE DATE,
	LAST_VERIFICATION_DATE DATE,
	PRIMARY KEY (SERIAL)
);

-- RRCU_STG_DEV.KEYSTONE_CORE.T_KS_ADDRESS_STG definition

create or replace TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_ADDRESS_STG_CF (
	ADDR_REC_KEY BIGINT,-- REPRESENT POINTER BACK TO DIM
	SOURCEHASH1 VARCHAR(32),  -- TYPE1 SOURCE HASHING
	SOURCEHASH2 VARCHAR(32),	-- TYPE2 SOURCE HASHING
	ISTYPE1	INT,  -- REPRESENTS TYPE 1
	ISTYPE2 INT,  -- REPRESENTS TYPE 2
	ISNEW INT, -- INDICATION FOR NEW RECORD	
	SERIAL NUMBER(19,0),
	LAST_FM_DATE DATE,
	TYPE_SERIAL NUMBER(19,0),
	ADDRESS_CHANGE_DATE DATE,
	ADDITIONAL_ADDRESS_LINE VARCHAR(50),
	STREET VARCHAR(50),
	CITY VARCHAR(40),
	STATE VARCHAR(40),
	POSTAL_CODE VARCHAR(20),
	COUNTRY VARCHAR(40),
	COUNTRY_CODE VARCHAR(2),
	CARRIER_ROUTE VARCHAR(4),
	ADDRESS_FORMAT VARCHAR(1),
	LATITUDE VARCHAR(11),
	LONGITUDE VARCHAR(11),
	ADDRESS_CONFIRMATION_DATE DATE,
	ADDRESS_CONFIRMATION_OPTION VARCHAR(1),
	PRIMARY KEY (SERIAL)
);

-- RRCU_STG_DEV.KEYSTONE_CORE.T_KS_PERSON_ID_STG definition

create or replace TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_PERSON_ID_STG_CF (
	PSNID_REC_KEY BIGINT,-- REPRESENT POINTER BACK TO DIM
	SOURCEHASH1 VARCHAR(32),  -- TYPE1 SOURCE HASHING
	SOURCEHASH2 VARCHAR(32),	-- TYPE2 SOURCE HASHING
	ISTYPE1	INT,  -- REPRESENTS TYPE 1
	ISTYPE2 INT,  -- REPRESENTS TYPE 2
	ISNEW INT, -- INDICATION FOR NEW RECORD	
	SERIAL NUMBER(19,0),
	PARENT_SERIAL NUMBER(19,0),
	ORDINAL NUMBER(19,0),
	CATEGORY VARCHAR(2),
	DESCRIPTION VARCHAR(40),
	VALUE VARCHAR(80),
	EXPIRATION_DATE DATE,
	ISSUER VARCHAR(40),
	ISSUE_DATE DATE,
	LAST_VERIFICATION_DATE DATE,
	LAST_FM_DATE DATE,
	PRIMARY KEY (SERIAL)
);

-- RRCU_STG_DEV.KEYSTONE_CORE.T_KS_SH_TYPE_STG definition

create or replace TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_SH_TYPE_STG_CF (
	SHTYP_REC_KEY BIGINT,-- REPRESENT POINTER BACK TO DIM
	SOURCEHASH1 VARCHAR(32),  -- TYPE1 SOURCE HASHING
	SOURCEHASH2 VARCHAR(32),	-- TYPE2 SOURCE HASHING
	ISTYPE1	INT,  -- REPRESENTS TYPE 1
	ISTYPE2 INT,  -- REPRESENTS TYPE 2
	ISNEW INT, -- INDICATION FOR NEW RECORD	
	SERIAL NUMBER(19,0),
	LAST_FM_DATE DATE,  -- IF value THEN expired
	DESCRIPTION VARCHAR(40),
	STATUS VARCHAR(1),
	CODE VARCHAR(40),
	CATEGORY VARCHAR(1),  -- C = closed so expire records
	PROCESSING VARCHAR(1),
	MINIMUM_BALANCE NUMBER(16,2),
	MINIMUM_DEPOSIT NUMBER(16,2),
	MINIMUM_WITHDRAWAL NUMBER(16,2),
	REG_D_LIMITING VARCHAR(1),
	REG_CC_OPTION VARCHAR(1),
	CLOSE_OPTION VARCHAR(1),
	CLOSE_FEE_SERIAL NUMBER(19,0),
	DORMANCY_RESTRICTION_DAYS NUMBER(5,0),
	CERT_BUMP_LIMIT NUMBER(5,0),
	CERT_BUMP_WAIT_DAYS NUMBER(5,0),
	COLLECTION_ITEM_TYPE_SERIAL NUMBER(19,0),
	COLLECTION_NOTICE_TYPE_SERIAL NUMBER(19,0),
	APP_FORM_PACKET_SERIAL NUMBER(19,0),
	DEF_LOGIN_WITHDRAWAL_ACCESS VARCHAR(1),
	DEF_LOGIN_DEPOSIT_ACCESS VARCHAR(1),
	DEF_LOGIN_INQUIRY_ACCESS VARCHAR(1),
	BALANCE_GL_SERIAL NUMBER(19,0),
	BALANCE_GL_BRANCH_ACCTING VARCHAR(1),
	CHARGE_OFF_GL_SERIAL NUMBER(19,0),
	CHARGE_OFF_GL_BRANCH_ACCTING VARCHAR(1),
	RECOVERY_GL_SERIAL NUMBER(19,0),
	RECOVERY_GL_BRANCH_ACCTING VARCHAR(1),
	DIVIDEND_GL_SERIAL NUMBER(19,0),
	DIVIDEND_GL_BRANCH_ACCTING VARCHAR(1),
	DIV_PAYABLE_GL_SERIAL NUMBER(19,0),
	DIV_PAYABLE_GL_BRANCH_ACCTING VARCHAR(1),
	CERT_PEN_GL_SERIAL NUMBER(19,0),
	CERT_PEN_GL_BRANCH_ACCTING VARCHAR(1),
	EXT_TRAN_GL_SERIAL NUMBER(19,0),
	EXT_TRAN_GL_BRANCH_ACCTING VARCHAR(1),
	AIRES_CODE VARCHAR(5),
	PRIMARY KEY (SERIAL)	
);

-- RRCU_STG_DEV.KEYSTONE_CORE.T_KS_LN_TYPE_STG definition

create or replace TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_LN_TYPE_STG_CF (
	LNTYP_REC_KEY BIGINT,-- REPRESENT POINTER BACK TO DIM
	SOURCEHASH1 VARCHAR(32),  -- TYPE1 SOURCE HASHING
	SOURCEHASH2 VARCHAR(32),	-- TYPE2 SOURCE HASHING
	ISTYPE1	INT,  -- REPRESENTS TYPE 1
	ISTYPE2 INT,  -- REPRESENTS TYPE 2
	ISNEW INT, -- INDICATION FOR NEW RECORD	
	SERIAL NUMBER(19,0),
	LAST_FM_DATE DATE,  -- IF value THEN expired
	DESCRIPTION VARCHAR(40),
	STATUS VARCHAR(1),
	CODE VARCHAR(40),
	CATEGORY VARCHAR(2),   -- C = closed so expire records
	PROCESSING VARCHAR(1),
	MINIMUM_BALANCE NUMBER(16,2),
	MINIMUM_ADVANCE NUMBER(16,2),
	CLOSE_OPTION VARCHAR(1),
	DORMANCY_RESTRICTION_DAYS NUMBER(5,0),
	DQ_RESTRICTION_GRACE_DAYS NUMBER(5,0),
	DQ_RESTRICTION_GRACE_AMOUNT NUMBER(16,2),
	DQ_RESTRICTION_FORCE_DAYS NUMBER(5,0),
	PAYMENT_HANDLING VARCHAR(1),
	PAYMENT_APPLICATION VARCHAR(4),
	PAYMENT_INTEREST_OPTION VARCHAR(1),
	PAYMENT_LATE_FEE_OPTION VARCHAR(1),
	PAYMENT_MAINTENANCE_FEE_OPTION VARCHAR(1),
	PAYMENT_PARTIAL_OPTION VARCHAR(1),
	PAYMENT_CALCULATION_SERIAL NUMBER(19,0),
	PAYMENT_AHEAD VARCHAR(1),
	PAYMENT_AHEAD_COUNT NUMBER(5,0),
	REPAYMENT_CALCULATION_SERIAL NUMBER(19,0),
	REPAYMENT_AHEAD VARCHAR(1),
	REPAYMENT_AHEAD_COUNT NUMBER(5,0),
	DRAW_PERIOD_EXPIRATION_MONTHS NUMBER(5,0),
	PAYMENT_SHORT_AMOUNT NUMBER(16,2),
	PAYMENT_SHORT_PERCENTAGE NUMBER(8,5),
	FIRST_DUE_DATE_CALCULATION VARCHAR(1),
	FIRST_DUE_DATE_GRACE_DAYS NUMBER(5,0),
	INTEREST_CALCULATION VARCHAR(1),
	CC_CALCULATION_SERIAL NUMBER(19,0),
	AVAILABLE_CALCULATION VARCHAR(1),
	CRED_REP_PORTFOLIO_TYPE VARCHAR(1),
	IRS_FORM_OPTION VARCHAR(1),
	GUARANTEE_OPTION VARCHAR(3),
	MLA_ELIGIBILITY VARCHAR(1),
	EXT_INTERFACE_SERIAL NUMBER(19,0),
	COLLECTION_ITEM_TYPE_SERIAL NUMBER(19,0),
	COLLECTION_NOTICE_TYPE_SERIAL NUMBER(19,0),
	PAPER_GRADE_SCALE_SERIAL NUMBER(19,0),
	RISK_BASED_PRICING_SERIAL NUMBER(19,0),
	RISK_BASED_PRICING_PLAN_SERIAL NUMBER(19,0),
	DECISION_MODEL_SERIAL NUMBER(19,0),
	DEALER_COMPENSATION_SERIAL NUMBER(19,0),
	APP_FORM_PACKET_SERIAL NUMBER(19,0),
	DEF_LOGIN_WITHDRAWAL_ACCESS VARCHAR(1),
	DEF_LOGIN_DEPOSIT_ACCESS VARCHAR(1),
	DEF_LOGIN_INQUIRY_ACCESS VARCHAR(1),
	BALANCE_GL_SERIAL NUMBER(19,0),
	BALANCE_GL_BRANCH_ACCTING VARCHAR(1),
	CHARGE_OFF_GL_SERIAL NUMBER(19,0),
	CHARGE_OFF_GL_BRANCH_ACCTING VARCHAR(1),
	RECOVERY_GL_SERIAL NUMBER(19,0),
	RECOVERY_GL_BRANCH_ACCTING VARCHAR(1),
	INTEREST_GL_SERIAL NUMBER(19,0),
	INTEREST_GL_BRANCH_ACCTING VARCHAR(1),
	INT_ACCRUED_GL_SERIAL NUMBER(19,0),
	INT_ACCRUED_GL_BRANCH_ACCTING VARCHAR(1),
	LATE_FEE_GL_SERIAL NUMBER(19,0),
	LATE_FEE_GL_BRANCH_ACCTING VARCHAR(1),
	EXT_TRAN_GL_SERIAL NUMBER(19,0),
	EXT_TRAN_GL_BRANCH_ACCTING VARCHAR(1),
	AIRES_CODE VARCHAR(5),
	INTEREST_PD_AHD_PAYOFF_OPTION VARCHAR(1),
	ORIGINAL_LN_DT_UPDATE_OPTION VARCHAR(1),
	UNAPP_FUNDS_GL_SERIAL NUMBER(19,0),
	UNAPP_FUNDS_GL_BRANCH_ACCTING VARCHAR(1),
	INSURANCE_PRODUCT_RESTRICTION VARCHAR(1),
	RIGHT_TO_RESCIND_DAYS NUMBER(5,0),
	INTEREST_PST_DUE_PAYOFF_OPTION VARCHAR(1),
	PRIMARY KEY (SERIAL)	
);

-- RRCU_STG_DEV.KEYSTONE_CORE.T_KS_RENTAL_TYPE_STG definition

create or replace TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_RENTAL_TYPE_STG_CF (
	RNTYP_REC_KEY BIGINT,-- REPRESENT POINTER BACK TO DIM
	SOURCEHASH1 VARCHAR(32),  -- TYPE1 SOURCE HASHING
	SOURCEHASH2 VARCHAR(32),	-- TYPE2 SOURCE HASHING
	ISTYPE1	INT,  -- REPRESENTS TYPE 1
	ISTYPE2 INT,  -- REPRESENTS TYPE 2
	ISNEW INT, -- INDICATION FOR NEW RECORD	
	SERIAL NUMBER(19,0),
	LAST_FM_DATE DATE,  -- IF value THEN expired
	DESCRIPTION VARCHAR(40),
	STATUS VARCHAR(1),
	CODE VARCHAR(40),
	CATEGORY VARCHAR(1),  -- C = closed so expire records
	TERM_OPTION VARCHAR(1),
	NEW_RENTAL_PRORATE_OPTION VARCHAR(1),
	SURRENDER_PRORATE_OPTION VARCHAR(1),
	FREQUENCY VARCHAR(2),
	FREQUENCY_DAY_1 NUMBER(5,0),
	FREQUENCY_DAY_2 NUMBER(5,0),
	NEXT_PERIOD_DATE DATE,
	FEE_SERIAL NUMBER(19,0),
	FEE_POSTING_POLICY_OPTION VARCHAR(1),
	ACCESS_FORM_TYPE_SERIAL NUMBER(19,0),
	PRIMARY KEY (SERIAL)	
);

-- RRCU_STG_DEV.KEYSTONE_CORE.T_KS_SHARE_STG definition

create or replace TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_SHARE_STG_CF (
	SHAR_REC_KEY BIGINT,-- REPRESENT POINTER BACK TO DIM
	SOURCEHASH1 VARCHAR(32),  -- TYPE1 SOURCE HASHING
	SOURCEHASH2 VARCHAR(32),	-- TYPE2 SOURCE HASHING
	ISTYPE1	INT,  -- REPRESENTS TYPE 1
	ISTYPE2 INT,  -- REPRESENTS TYPE 2
	ISNEW INT, -- INDICATION FOR NEW RECORD	
	SERIAL NUMBER(19,0),
	PARENT_SERIAL NUMBER(19,0),
	STORED_ACCESS_KEY VARCHAR(200),
	ORDINAL NUMBER(19,0),
	LAST_FM_DATE DATE,
	ID VARCHAR(4),
	DESCRIPTION VARCHAR(40),
	TYPE_SERIAL NUMBER(19,0),
	PROCESSING VARCHAR(1),
	BRANCH_SERIAL NUMBER(19,0),
	OPEN_DATE DATE,
	OPENED_BY_USER_SERIAL NUMBER(19,0),
	CLOSE_DATE DATE,
	CLOSE_REASON_SERIAL NUMBER(19,0),
	CHARGE_OFF_TYPE_SERIAL NUMBER(19,0),
	CHARGE_OFF_DATE DATE,
	CHARGE_OFF_AMOUNT NUMBER(16,2),
	COLLECTION_STATUS VARCHAR(1),
	COLLECTION_HANDLING VARCHAR(2),
	COLLECTION_NOTICE_COUNT NUMBER(5,0),
	COLLECTION_NOTICE_DATE DATE,
	CRED_REP_PRIMARY_ECOA_CODE VARCHAR(1),
	CRED_REP_PRIMARY_CONS_INFO_IND VARCHAR(2),
	CRED_REP_BANKRUPTCY_DATE DATE,
	CRED_REP_ACCOUNT_TYPE VARCHAR(2),
	CRED_REP_SPEC_COMM_CODE VARCHAR(2),
	CRED_REP_COMP_COND_CODE VARCHAR(2),
	CRED_REP_FIRST_DQ_DATE DATE,
	CRED_REP_ACCOUNT_STATUS VARCHAR(2),
	CRED_REP_LAST_DATE DATE,
	SHARED_BRANCH_OPTION VARCHAR(1),
	NOTE_RESTRICTION VARCHAR(1),
	DEPOSIT_RESTRICTION VARCHAR(1),
	WITHDRAWAL_RESTRICTION VARCHAR(1),
	MONETARY_PURGE_DATE DATE,
	LAST_MONETARY_DATE DATE,
	LAST_ACTIVITY_DATE DATE,
	BALANCE NUMBER(16,2),
	MINIMUM_BALANCE NUMBER(16,2),
	MINIMUM_DEPOSIT NUMBER(16,2),
	MINIMUM_WITHDRAWAL NUMBER(16,2),
	SWEEP_OPTION VARCHAR(1),
	SWEEP_TARGET_BALANCE NUMBER(16,2),
	SWEEP_MINIMUM_BALANCE NUMBER(16,2),
	SWEEP_MAXIMUM_BALANCE NUMBER(16,2),
	COURTESY_PAY_LIMIT NUMBER(16,2),
	COURTESY_PAY_RESTRICT_SERIAL NUMBER(19,0),
	COURTESY_PAY_ATM_DEBIT VARCHAR(1),
	COURTESY_PAY_ATM_DEBIT_CH_DATE DATE,
	COURTESY_PAY_OTHER VARCHAR(1),
	COURTESY_PAY_OTHER_CH_DATE DATE,
	POSITIVE_PAY_OPTION VARCHAR(1),
	CK_HLD_NEXT_DAY_AVAIL_AMOUNT NUMBER(16,2),
	OPENING_BALANCE NUMBER(16,2),
	ORIGINAL_AMOUNT NUMBER(16,2),
	ORIGINAL_DATE DATE,
	CERT_NUMBER VARCHAR(20),
	CERT_PEN_CALCULATION_SERIAL NUMBER(19,0),
	CERT_PEN_WAIVE_COUNT NUMBER(5,0),
	CERT_PEN_WAIVE_LAST_DATE DATE,
	CERT_DIVIDENDS_AVAILABLE NUMBER(16,2),
	CERT_OID_YIELD_TO_MATURITY NUMBER(8,5),
	CERT_OID_BALANCE NUMBER(16,2),
	CERT_BUMP_COUNT NUMBER(5,0),
	CERT_BUMP_LAST_DATE DATE,
	MATURITY_POSTING VARCHAR(1),
	MATURITY_FREQUENCY VARCHAR(1),
	MATURITY_PERIOD NUMBER(5,0),
	MATURITY_DATE DATE,
	MATURITY_LAST_DATE DATE,
	MATURITY_RENEW_DEFAULTS_SERIAL NUMBER(19,0),
	MAIL_PERSON_ADDR_LINK_SERIAL NUMBER(19,0),
	STMT_MAIL_GROUP_SERIAL NUMBER(19,0),
	STMT_CUTOFF_GROUP_SERIAL NUMBER(19,0),
	STMT_CUTOFF_LAST_DATE DATE,
	STMT_CUTOFF_LAST_TRAN_SERIAL NUMBER(19,0),
	STMT_CUTOFF_PRIOR_DATE DATE,
	STMT_CUTOFF_PRIOR_TRAN_SERIAL NUMBER(19,0),
	STMT_REG_E_COUNT NUMBER(5,0),
	ANALYSIS_CATEGORY VARCHAR(1),
	ANALYSIS_SHARE_SERIAL NUMBER(19,0),
	TAX_PERSON_SERIAL NUMBER(19,0),
	TAX_PLAN_CATEGORY VARCHAR(2),
	TAX_PLAN_SERIAL NUMBER(19,0),
	DIVIDEND_CALCULATION_SERIAL NUMBER(19,0),
	DIVIDEND_POSTING VARCHAR(1),
	DIVIDEND_CUSTOM_RATE NUMBER(8,5),
	DIVIDEND_LAST_AMOUNT NUMBER(16,2),
	DIVIDEND_LAST_DATE DATE,
	DIVIDEND_ACCRUED_DATE DATE,
	DIVIDEND_ACCRUED_AMOUNT NUMBER(16,2),
	DIVIDEND_APYE_START_DATE DATE,
	DIVIDEND_APYE_DAILY_BAL NUMBER(16,2),
	ACH_DEPOSIT_LAST_AMOUNT NUMBER(16,2),
	ACH_DEPOSIT_LAST_DATE DATE,
	REG_D_COUNT NUMBER(5,0),
	REG_D_COUNT_PRIOR NUMBER(5,0),
	REG_D_PAY VARCHAR(1),
	REG_D_PAY_CH_DATE DATE,
	CRED_REP_PRIMARY_CONS_FIN_DATE DATE,
	PRIMARY KEY (SERIAL)	
);

-- RRCU_STG_DEV.KEYSTONE_CORE.T_KS_LOAN_STG definition

create or replace TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_LOAN_STG_CF (
	LOAN_REC_KEY BIGINT,-- REPRESENT POINTER BACK TO DIM
	SOURCEHASH1 VARCHAR(32),  -- TYPE1 SOURCE HASHING
	SOURCEHASH2 VARCHAR(32),	-- TYPE2 SOURCE HASHING
	ISTYPE1	INT,  -- REPRESENTS TYPE 1
	ISTYPE2 INT,  -- REPRESENTS TYPE 2
	ISNEW INT, -- INDICATION FOR NEW RECORD	
	SERIAL NUMBER(19,0),
	PARENT_SERIAL NUMBER(19,0),
	STORED_ACCESS_KEY VARCHAR(200),
	ORDINAL NUMBER(19,0),
	LAST_FM_DATE DATE,
	ID VARCHAR(4),
	DESCRIPTION VARCHAR(40),
	TYPE_SERIAL NUMBER(19,0),
	PROCESSING VARCHAR(1),
	EXTERNAL_ACCOUNT_NUMBER VARCHAR(19),
	EXTERNAL_INVESTOR_BANK_CODE VARCHAR(10),
	EXTERNAL_INVESTOR_CODE VARCHAR(10),
	EXTERNAL_INVESTOR_GROUP_CODE VARCHAR(10),
	LAST_IMPORT_DATE DATE,
	BRANCH_SERIAL NUMBER(19,0),
	OPEN_DATE DATE,
	OPENED_BY_USER_SERIAL NUMBER(19,0),
	CLOSE_DATE DATE,
	CLOSE_REASON_SERIAL NUMBER(19,0),
	SHADOW_DATE DATE,
	SHADOW_BALANCE NUMBER(16,2),
	SHADOW_INTEREST NUMBER(16,2),
	SHADOW_LATE_FEE NUMBER(16,2),
	CHARGE_OFF_DATE DATE,
	CHARGE_OFF_TYPE_SERIAL NUMBER(19,0),
	CHARGE_OFF_AMOUNT NUMBER(16,2),
	COLLECTION_STATUS VARCHAR(1),
	COLLECTION_HANDLING VARCHAR(2),
	COLLECTION_NOTICE_COUNT NUMBER(5,0),
	COLLECTION_NOTICE_DATE DATE,
	BANKRUPTCY_INDICATOR VARCHAR(2),
	CRED_REP_PRIMARY_ECOA_CODE VARCHAR(1),
	CRED_REP_PRIMARY_CONS_INFO_IND VARCHAR(2),
	CRED_REP_BANKRUPTCY_DATE DATE,
	CRED_REP_ACCOUNT_TYPE VARCHAR(2),
	CRED_REP_PORTFOLIO_TYPE_OVR VARCHAR(1),
	CRED_REP_SPEC_COMM_CODE VARCHAR(2),
	CRED_REP_COMP_COND_CODE VARCHAR(2),
	CRED_REP_FIRST_DQ_DATE DATE,
	CRED_REP_ACCOUNT_STATUS VARCHAR(2),
	CRED_REP_PMT_HISTORY_PROFILE VARCHAR(24),
	CRED_REP_LAST_DATE DATE,
	SHARED_BRANCH_OPTION VARCHAR(1),
	NOTE_RESTRICTION VARCHAR(1),
	MONETARY_PURGE_DATE DATE,
	LAST_MONETARY_DATE DATE,
	LAST_ACTIVITY_DATE DATE,
	LAST_ADVANCE_DATE DATE,
	MATURITY_DATE DATE,
	PURPOSE_SERIAL NUMBER(19,0),
	PROCESSOR_USER_SERIAL NUMBER(19,0),
	APPROVAL_OFFICER_SERIAL NUMBER(19,0),
	APPROVAL_DATE DATE,
	APPLICATION_SERIAL NUMBER(19,0),
	CREDIT_SCORE_CATEGORY VARCHAR(3),
	CREDIT_SCORE NUMBER(10,0),
	PAPER_GRADE_SERIAL NUMBER(19,0),
	COLLATERAL_TYPE_SERIAL NUMBER(19,0),
	NOTE_NUMBER VARCHAR(20),
	BALANCE NUMBER(16,2),
	UNAPPLIED_FUNDS_BALANCE NUMBER(16,2),
	MINIMUM_BALANCE NUMBER(16,2),
	MINIMUM_ADVANCE NUMBER(16,2),
	DOWN_PAYMENT NUMBER(16,2),
	MASTER_LINE_SERIAL NUMBER(19,0),
	CREDIT_LIMIT NUMBER(16,2),
	CREDIT_LIMIT_EXPIRATION_DATE DATE,
	CREDIT_LIMIT_SHARED_GRP_SERIAL NUMBER(19,0),
	CC_CASH_ADV_LIMIT_PERCENTAGE NUMBER(8,5),
	CC_CASH_ADV_LIMIT_AMOUNT NUMBER(16,2),
	POSITIVE_PAY_OPTION VARCHAR(1),
	DRAW_PERIOD_EXPIRATION_DATE DATE,
	DRAW_PERIOD_STATUS VARCHAR(1),
	NON_REVOLVING_BALANCE NUMBER(16,2),
	MAX_VALUATION_CREDIT_LIMIT NUMBER(16,2),
	ORIGINAL_LOAN_DATE DATE,
	ORIGINAL_FUNDING_DATE DATE,
	ORIGINAL_DUE_DATE DATE,
	ORIGINAL_BALANCE NUMBER(16,2),
	ACQUISITION_DATE DATE,
	ACQUISITION_BALANCE NUMBER(16,2),
	SHARE_SECURED_OPTION VARCHAR(1),
	SHARE_SECURED_AMOUNT NUMBER(16,2),
	PAYMENT_METHOD VARCHAR(1),
	PAYMENT_COUPON_DATE DATE,
	PAYMENT_AMOUNT NUMBER(16,2),
	PAYMENT_PARTIAL_AMOUNT NUMBER(16,2),
	PAYMENT_CALCULATION_SERIAL NUMBER(19,0),
	PAYMENT_CALCULATION_STATUS VARCHAR(1),
	PAYMENT_CALCULATION_SCH_FREQ VARCHAR(2),
	PAYMENT_CALCULATION_SCH_FREQ_1 NUMBER(5,0),
	PAYMENT_CALCULATION_SCH_PERIOD NUMBER(5,0),
	PAYMENT_CALCULATION_SCH_DATE DATE,
	PAYMENT_COUNT_SCHEDULED NUMBER(5,0),
	PAYMENT_COUNT_MADE NUMBER(5,0),
	PAYMENT_COUNT_DQ_UNDER_30 NUMBER(5,0),
	PAYMENT_COUNT_DQ_30_TO_59 NUMBER(5,0),
	PAYMENT_COUNT_DQ_60_TO_89 NUMBER(5,0),
	PAYMENT_COUNT_DQ_90_TO_119 NUMBER(5,0),
	PAYMENT_COUNT_DQ_120_AND_UP NUMBER(5,0),
	PAYMENT_LAST_DATE DATE,
	PAYMENT_FREQUENCY VARCHAR(2),
	PAYMENT_FREQUENCY_DAY_1 NUMBER(5,0),
	PAYMENT_FREQUENCY_DAY_2 NUMBER(5,0),
	PAYMENT_SKIP_COUNT NUMBER(5,0),
	PAYMENT_SKIP_START_MONTH NUMBER(5,0),
	PAYMENT_SKIP_START_DAY NUMBER(5,0),
	PAYMENT_AHEAD VARCHAR(1),
	PAYMENT_AHEAD_COUNT NUMBER(5,0),
	PAYMENT_DUE_DATE DATE,
	ACH_PAYMENT_LAST_AMOUNT NUMBER(16,2),
	ACH_PAYMENT_LAST_DATE DATE,
	BALLOON_DATE DATE,
	BALLOON_AMOUNT NUMBER(16,2),
	INTEREST_PAID_TOTAL NUMBER(16,2),
	INTEREST_UNPAID NUMBER(16,2),
	INTEREST_ONLY_UNPAID NUMBER(16,2),
	INTEREST_PREPAID NUMBER(16,2),
	INTEREST_CALCULATION_DATE DATE,
	INTEREST_RATE NUMBER(8,5),
	INTEREST_APR NUMBER(8,5),
	INTEREST_RATE_VAR_OPT VARCHAR(1),
	INTEREST_RATE_INDEX_SERIAL NUMBER(19,0),
	INTEREST_RATE_MARGIN NUMBER(8,5),
	INTEREST_RATE_DISCOUNT NUMBER(8,5),
	INTEREST_RATE_RISK_PREMIUM NUMBER(8,5),
	INTEREST_RATE_MINIMUM NUMBER(8,5),
	INTEREST_RATE_MAXIMUM NUMBER(8,5),
	INTEREST_RATE_CHG_START_DATE DATE,
	INTEREST_RATE_CHG_SCH_FREQ VARCHAR(2),
	INTEREST_RATE_CHG_SCH_FREQ_1 NUMBER(5,0),
	INTEREST_RATE_CHG_SCH_FREQ_2 NUMBER(5,0),
	INTEREST_RATE_CHG_SCH_PERIOD NUMBER(5,0),
	INTEREST_RATE_CHG_SCH_DATE DATE,
	INTEREST_RATE_CHG_SCH_RND_INC NUMBER(8,5),
	INTEREST_RATE_CHG_SCH_RND_OPT VARCHAR(2),
	INTEREST_RATE_CAP_FREQUENCY VARCHAR(1),
	INTEREST_RATE_CAP_PERIOD NUMBER(5,0),
	INTEREST_RATE_CAP_DIRECTION VARCHAR(1),
	INTEREST_RATE_CAP_START_DATE DATE,
	INTEREST_RATE_CAP_START_RATE NUMBER(8,5),
	INTEREST_RATE_CAP NUMBER(8,5),
	INTEREST_RATE_ADJUSTMENT NUMBER(8,5),
	INTEREST_RATE_ADJ_RSN_SERIAL NUMBER(19,0),
	LATE_FEE_UNPAID NUMBER(16,2),
	LATE_FEE_CALCULATION_SERIAL NUMBER(19,0),
	LATE_FEE_CALCULATION_DATE DATE,
	LATE_FEE_CALCULATION_ACCR NUMBER(16,2),
	MAINTENANCE_FEE_SERIAL NUMBER(19,0),
	MAINTENANCE_FEE_EFFECT_DATE DATE,
	MAINTENANCE_FEE_EXPIRE_DATE DATE,
	MAINTENANCE_FEE_UNPAID NUMBER(16,2),
	IMPOUND_AMOUNT NUMBER(16,2),
	IMPOUND_PARTIAL_AMOUNT NUMBER(16,2),
	IMPOUND_SHARE_SERIAL NUMBER(19,0),
	FASB_91_TYPE_SERIAL NUMBER(19,0),
	FASB_91_ORIGINAL_APR NUMBER(8,5),
	FASB_91_EFFECTIVE_APR NUMBER(8,5),
	FASB_91_UNAMORTIZED_FEES NUMBER(16,2),
	FASB_91_AMORTIZATION_AMOUNT NUMBER(16,2),
	FASB_91_FUNDING_OPTION VARCHAR(1),
	MAIL_PERSON_ADDR_LINK_SERIAL NUMBER(19,0),
	STMT_MAIL_GROUP_SERIAL NUMBER(19,0),
	STMT_CUTOFF_GROUP_SERIAL NUMBER(19,0),
	STMT_CUTOFF_LAST_DATE DATE,
	STMT_CUTOFF_LAST_TRAN_SERIAL NUMBER(19,0),
	STMT_CUTOFF_PRIOR_DATE DATE,
	STMT_CUTOFF_PRIOR_TRAN_SERIAL NUMBER(19,0),
	STMT_REG_E_COUNT NUMBER(5,0),
	CC_PURCH_BAL_OLD NUMBER(16,2),
	CC_PURCH_BAL_NEW NUMBER(16,2),
	CC_PURCH_AVG_BAL NUMBER(16,2),
	CC_PURCH_INT_RATE NUMBER(8,5),
	CC_PURCH_INT_RATE_VAR_OPT VARCHAR(1),
	CC_PURCH_INT_CHARGE NUMBER(16,2),
	CC_PURCH_INT_UNPAID_OLD NUMBER(16,2),
	CC_PURCH_INT_UNPAID_NEW NUMBER(16,2),
	CC_PURCH_GRACE_IND_OLD VARCHAR(1),
	CC_PURCH_GRACE_IND_NEW VARCHAR(1),
	CC_CASH_ADV_BAL_OLD NUMBER(16,2),
	CC_CASH_ADV_BAL_NEW NUMBER(16,2),
	CC_CASH_ADV_AVG_BAL NUMBER(16,2),
	CC_CASH_ADV_INT_RATE NUMBER(8,5),
	CC_CASH_ADV_INT_RATE_VAR_OPT VARCHAR(1),
	CC_CASH_ADV_INT_CHARGE NUMBER(16,2),
	CC_CASH_ADV_INT_UNPAID_OLD NUMBER(16,2),
	CC_CASH_ADV_INT_UNPAID_NEW NUMBER(16,2),
	CC_CASH_ADV_GRACE_IND_OLD VARCHAR(1),
	CC_CASH_ADV_GRACE_IND_NEW VARCHAR(1),
	CC_BAL_XFR_BAL_OLD NUMBER(16,2),
	CC_BAL_XFR_BAL_NEW NUMBER(16,2),
	CC_BAL_XFR_AVG_BAL NUMBER(16,2),
	CC_BAL_XFR_INT_RATE NUMBER(8,5),
	CC_BAL_XFR_INT_RATE_VAR_OPT VARCHAR(1),
	CC_BAL_XFR_INT_CHARGE NUMBER(16,2),
	CC_BAL_XFR_INT_UNPAID_OLD NUMBER(16,2),
	CC_BAL_XFR_INT_UNPAID_NEW NUMBER(16,2),
	CC_BAL_XFR_GRACE_IND_OLD VARCHAR(1),
	CC_BAL_XFR_GRACE_IND_NEW VARCHAR(1),
	CC_FEE_BAL_OLD NUMBER(16,2),
	CC_FEE_BAL_NEW NUMBER(16,2),
	CC_TOTAL_BAL_OLD NUMBER(16,2),
	CC_TOTAL_BAL_NEW NUMBER(16,2),
	CC_FIRST_YEAR_FEES_MAXIMUM NUMBER(16,2),
	CC_FIRST_YEAR_FEES_CHARGED NUMBER(16,2),
	CC_PENALTY_INT_RATE NUMBER(8,5),
	PROMO_RATE_TYPE_SERIAL NUMBER(19,0),
	SEGMENT_COUNT_LIMIT NUMBER(5,0),
	TAX_PERSON_SERIAL NUMBER(19,0),
	MLA_LIMITATION VARCHAR(1),
	PARTICIPATION_POOL_SERIAL NUMBER(19,0),
	LIFE_INSURANCE_SERIAL NUMBER(19,0),
	DISABILITY_INSURANCE_SERIAL NUMBER(19,0),
	SINGLE_PREMIUM_LIFE NUMBER(16,2),
	SINGLE_PREMIUM_DISABILITY NUMBER(16,2),
	INSURANCE_METHOD VARCHAR(1),
	INSURANCE_SHARE_SERIAL NUMBER(19,0),
	ROW_CHANGE_TIMESTAMP TIMESTAMP_NTZ(9),
	SHARED_COLLATERAL_OPTION VARCHAR(1),
	CRED_REP_PRIMARY_CONS_FIN_DATE DATE,
	PRIMARY KEY (SERIAL)	
);

-- RRCU_STG_DEV.KEYSTONE_CORE.T_KS_RENTAL_STG definition

create or replace TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_RENTAL_STG_CF (
	RENT_REC_KEY BIGINT,-- REPRESENT POINTER BACK TO DIM
	SOURCEHASH1 VARCHAR(32),  -- TYPE1 SOURCE HASHING
	SOURCEHASH2 VARCHAR(32),	-- TYPE2 SOURCE HASHING
	ISTYPE1	INT,  -- REPRESENTS TYPE 1
	ISTYPE2 INT,  -- REPRESENTS TYPE 2
	ISNEW INT, -- INDICATION FOR NEW RECORD	
	SERIAL NUMBER(19,0),
	LAST_FM_DATE DATE,
	DESCRIPTION VARCHAR(40),
	TYPE_SERIAL NUMBER(19,0),
	BRANCH_SERIAL NUMBER(19,0),
	STATUS VARCHAR(1),
	STATUS_DATE DATE,
	STATUS_COMMENT VARCHAR(200),
	AVAILABLE_DATE DATE,
	RENTAL_START_DATE DATE,
	LAST_FEE_AMOUNT NUMBER(16,2),
	LAST_FEE_DATE DATE,
	NEXT_FEE_DATE DATE,
	NSF_FEE_DATE DATE,
	SHARE_SERIAL NUMBER(19,0),
	LOAN_SERIAL NUMBER(19,0),
	KEY_COUNT NUMBER(5,0),
	SERIAL_NUMBER VARCHAR(20),
	ASSET_NUMBER VARCHAR(20),
	ADDITIONAL_INFORMATION VARCHAR(200),
	PRIMARY KEY (SERIAL)	
);

-- RRCU_STG_DEV.KEYSTONE_CORE.T_KS_COLLATERAL_STG definition

create or replace TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_COLLATERAL_STG_CF (
	COLL_REC_KEY BIGINT,-- REPRESENT POINTER BACK TO DIM
	SOURCEHASH1 VARCHAR(32),  -- TYPE1 SOURCE HASHING
	SOURCEHASH2 VARCHAR(32),	-- TYPE2 SOURCE HASHING
	ISTYPE1	INT,  -- REPRESENTS TYPE 1
	ISTYPE2 INT,  -- REPRESENTS TYPE 2
	ISNEW INT, -- INDICATION FOR NEW RECORD	
	SERIAL NUMBER(19,0),
	PARENT_SERIAL NUMBER(19,0),
	PROPERTY_ADDRESS_SERIAL NUMBER(19,0),
	ORDINAL NUMBER(19,0),
	LAST_FM_DATE DATE,
	TYPE_SERIAL NUMBER(19,0),
	CATEGORY VARCHAR(1),
	AMOUNT NUMBER(16,2),
	PRIMARY KEY (SERIAL)	
);

-- RRCU_STG_DEV.KEYSTONE_CORE.T_KS_BRANCH_STG definition

create or replace TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_BRANCH_STG_CF (
	BRCH_REC_KEY BIGINT,-- REPRESENT POINTER BACK TO DIM
	SOURCEHASH1 VARCHAR(32),  -- TYPE1 SOURCE HASHING
	SOURCEHASH2 VARCHAR(32),	-- TYPE2 SOURCE HASHING
	ISTYPE1	INT,  -- REPRESENTS TYPE 1
	ISTYPE2 INT,  -- REPRESENTS TYPE 2
	ISNEW INT, -- INDICATION FOR NEW RECORD	
	SERIAL NUMBER(19,0),
	LAST_FM_DATE DATE,
	DESCRIPTION VARCHAR(40),
	STATUS VARCHAR(1),
	CODE VARCHAR(40),
	GL_ACCOUNT_BRANCH_SUFFIX VARCHAR(4),
	CK_HLD_ROUTING_SET_SERIAL NUMBER(19,0),
	CK_HLD_BANK_DAY_CUTOFF_HOUR NUMBER(5,0),
	CK_HLD_BANK_DAY_CUTOFF_MINUTE NUMBER(5,0),
	TIME_ZONE VARCHAR(7),
	PHONE_NUMBER VARCHAR(40),
	SHARED_BRANCH_CUSO VARCHAR(1),
	SHARED_BRANCH_LEAGUE VARCHAR(2),
	SHARED_BRANCH_INSTITUTION_ID VARCHAR(9),
	SHARED_BRANCH_PSEUDO_TERMINAL VARCHAR(6),
	CHEX_SYSTEMS_CUSTOMER_ID VARCHAR(8),
	CHEX_SYSTEMS_BIZ_CHEX_FI_ID VARCHAR(8),
	FINCEN_LOCATION_CODE VARCHAR(10),
	RSSD_ID VARCHAR(10),
	SALES_OPPORTUNITY_OPTION VARCHAR(1),
	FIRST_ADDRESS_LINE VARCHAR(50),
	PO_BOX VARCHAR(50),
	ADDITIONAL_ADDRESS_LINE VARCHAR(50),
	STREET VARCHAR(50),
	CITY VARCHAR(40),
	STATE VARCHAR(40),
	POSTAL_CODE VARCHAR(20),
	COUNTRY VARCHAR(40),
	COUNTRY_CODE VARCHAR(2),
	ADDRESS_FORMAT VARCHAR(1),
	LATITUDE VARCHAR(11),
	LONGITUDE VARCHAR(11),
	NMLSR_ID VARCHAR(12),
	NMLSR_STATE VARCHAR(2),
	NMLSR_EFFECTIVE_DATE DATE,
	NMLSR_EXPIRATION_DATE DATE,
	PRIMARY KEY (SERIAL)	
);

-- RRCU_STG_DEV.KEYSTONE_CORE.T_KS_LOAN_REQUEST_STG definition

create or replace TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_LOAN_REQUEST_STG_CF(
	LNRQ_REC_KEY BIGINT,-- REPRESENT POINTER BACK TO DIM
	SOURCEHASH1 VARCHAR(32),  -- TYPE1 SOURCE HASHING
	SOURCEHASH2 VARCHAR(32),	-- TYPE2 SOURCE HASHING
	ISTYPE1	INT,  -- REPRESENTS TYPE 1
	ISTYPE2 INT,  -- REPRESENTS TYPE 2
	ISNEW INT, -- INDICATION FOR NEW RECORD	
	SERIAL NUMBER(19,0),
	PARENT_SERIAL NUMBER(19,0),
	ORDINAL NUMBER(19,0),
	LAST_FM_DATE DATE,
	ID VARCHAR(4),
	DESCRIPTION VARCHAR(40),
	TYPE_SERIAL NUMBER(19,0),
	BRANCH_SERIAL NUMBER(19,0),
	CRED_REP_PRIMARY_ECOA_CODE VARCHAR(1),
	CRED_REP_ACCOUNT_TYPE VARCHAR(2),
	CRED_REP_PORTFOLIO_TYPE_OVR VARCHAR(1),
	SHARED_BRANCH_OPTION VARCHAR(1),
	SOURCE_LOAN_SERIAL NUMBER(19,0),
	PROJECTION_DESCRIPTION VARCHAR(40),
	PROJECTION_METHOD VARCHAR(1),
	MATURITY_DATE DATE,
	PURPOSE_SERIAL NUMBER(19,0),
	PROCESSOR_USER_SERIAL NUMBER(19,0),
	APPROVAL_OFFICER_SERIAL NUMBER(19,0),
	APPROVAL_DATE DATE,
	APPROVED_LOAN_SERIAL NUMBER(19,0),
	CREDIT_SCORE_CATEGORY VARCHAR(3),
	CREDIT_SCORE NUMBER(10,0),
	PAPER_GRADE_SERIAL NUMBER(19,0),
	COLLATERAL_TYPE_SERIAL NUMBER(19,0),
	NOTE_NUMBER VARCHAR(20),
	MINIMUM_BALANCE NUMBER(16,2),
	MINIMUM_ADVANCE NUMBER(16,2),
	DOWN_PAYMENT NUMBER(16,2),
	CREDIT_LIMIT NUMBER(16,2),
	CREDIT_LIMIT_EXPIRATION_DATE DATE,
	CREDIT_LIMIT_SHARED_GRP_SERIAL NUMBER(19,0),
	CC_CASH_ADV_LIMIT_PERCENTAGE NUMBER(8,5),
	CC_CASH_ADV_LIMIT_AMOUNT NUMBER(16,2),
	POSITIVE_PAY_OPTION VARCHAR(1),
	DRAW_PERIOD_EXPIRATION_DATE DATE,
	MAX_VALUATION_CREDIT_LIMIT NUMBER(16,2),
	SHARE_SECURED_OPTION VARCHAR(1),
	SHARE_SECURED_AMOUNT NUMBER(16,2),
	PAYMENT_METHOD VARCHAR(1),
	PAYMENT_AMOUNT NUMBER(16,2),
	PAYMENT_CALCULATION_SERIAL NUMBER(19,0),
	PAYMENT_CALCULATION_SCH_FREQ VARCHAR(2),
	PAYMENT_CALCULATION_SCH_FREQ_1 NUMBER(5,0),
	PAYMENT_CALCULATION_SCH_PERIOD NUMBER(5,0),
	PAYMENT_CALCULATION_SCH_DATE DATE,
	PAYMENT_COUNT_SCHEDULED NUMBER(5,0),
	PAYMENT_FREQUENCY VARCHAR(2),
	PAYMENT_FREQUENCY_DAY_1 NUMBER(5,0),
	PAYMENT_FREQUENCY_DAY_2 NUMBER(5,0),
	PAYMENT_SKIP_COUNT NUMBER(5,0),
	PAYMENT_SKIP_START_MONTH NUMBER(5,0),
	PAYMENT_SKIP_START_DAY NUMBER(5,0),
	PAYMENT_AHEAD VARCHAR(1),
	PAYMENT_AHEAD_COUNT NUMBER(5,0),
	PAYMENT_DUE_DATE DATE,
	BALLOON_DATE DATE,
	BALLOON_AMOUNT NUMBER(16,2),
	INTEREST_PREPAID NUMBER(16,2),
	INTEREST_CALCULATION_DATE DATE,
	INTEREST_RATE NUMBER(8,5),
	INTEREST_APR NUMBER(8,5),
	INTEREST_RATE_VAR_OPT VARCHAR(1),
	INTEREST_RATE_INDEX_SERIAL NUMBER(19,0),
	INTEREST_RATE_MARGIN NUMBER(8,5),
	INTEREST_RATE_DISCOUNT NUMBER(8,5),
	INTEREST_RATE_RISK_PREMIUM NUMBER(8,5),
	INTEREST_RATE_MINIMUM NUMBER(8,5),
	INTEREST_RATE_MAXIMUM NUMBER(8,5),
	INTEREST_RATE_CHG_START_DATE DATE,
	INTEREST_RATE_CHG_SCH_FREQ VARCHAR(2),
	INTEREST_RATE_CHG_SCH_FREQ_1 NUMBER(5,0),
	INTEREST_RATE_CHG_SCH_FREQ_2 NUMBER(5,0),
	INTEREST_RATE_CHG_SCH_PERIOD NUMBER(5,0),
	INTEREST_RATE_CHG_SCH_DATE DATE,
	INTEREST_RATE_CHG_SCH_RND_INC NUMBER(8,5),
	INTEREST_RATE_CHG_SCH_RND_OPT VARCHAR(2),
	INTEREST_RATE_CAP_FREQUENCY VARCHAR(1),
	INTEREST_RATE_CAP_PERIOD NUMBER(5,0),
	INTEREST_RATE_CAP_DIRECTION VARCHAR(1),
	INTEREST_RATE_CAP_START_DATE DATE,
	INTEREST_RATE_CAP_START_RATE NUMBER(8,5),
	INTEREST_RATE_CAP NUMBER(8,5),
	INTEREST_RATE_ADJUSTMENT NUMBER(8,5),
	INTEREST_RATE_ADJ_RSN_SERIAL NUMBER(19,0),
	LATE_FEE_CALCULATION_SERIAL NUMBER(19,0),
	MAINTENANCE_FEE_SERIAL NUMBER(19,0),
	MAINTENANCE_FEE_EFFECT_DATE DATE,
	MAINTENANCE_FEE_EXPIRE_DATE DATE,
	IMPOUND_AMOUNT NUMBER(16,2),
	IMPOUND_SHARE_SERIAL NUMBER(19,0),
	FASB_91_TYPE_SERIAL NUMBER(19,0),
	FASB_91_ORIGINAL_APR NUMBER(8,5),
	FASB_91_EFFECTIVE_APR NUMBER(8,5),
	FASB_91_UNAMORTIZED_FEES NUMBER(16,2),
	FASB_91_AMORTIZATION_AMOUNT NUMBER(16,2),
	FASB_91_FUNDING_OPTION VARCHAR(1),
	MAIL_PERSON_ADDR_LINK_SERIAL NUMBER(19,0),
	STMT_MAIL_GROUP_SERIAL NUMBER(19,0),
	STMT_CUTOFF_GROUP_SERIAL NUMBER(19,0),
	CC_PURCH_INT_RATE NUMBER(8,5),
	CC_PURCH_INT_RATE_VAR_OPT VARCHAR(1),
	CC_CASH_ADV_INT_RATE NUMBER(8,5),
	CC_CASH_ADV_INT_RATE_VAR_OPT VARCHAR(1),
	CC_BAL_XFR_INT_RATE NUMBER(8,5),
	CC_BAL_XFR_INT_RATE_VAR_OPT VARCHAR(1),
	CC_FIRST_YEAR_FEES_MAXIMUM NUMBER(16,2),
	CC_PENALTY_INT_RATE NUMBER(8,5),
	PROMO_RATE_TYPE_SERIAL NUMBER(19,0),
	SEGMENT_COUNT_LIMIT NUMBER(5,0),
	TAX_PERSON_SERIAL NUMBER(19,0),
	MLA_LIMITATION VARCHAR(1),
	LIFE_INSURANCE_SERIAL NUMBER(19,0),
	DISABILITY_INSURANCE_SERIAL NUMBER(19,0),
	SINGLE_PREMIUM_LIFE NUMBER(16,2),
	SINGLE_PREMIUM_DISABILITY NUMBER(16,2),
	INSURANCE_METHOD VARCHAR(1),
	INSURANCE_SHARE_SERIAL NUMBER(19,0),
	WITHDRAWN_INDICATOR VARCHAR(1),
	CONTRACT_DATE DATE,
	SHARED_COLLATERAL_OPTION VARCHAR(1),
	PRIMARY KEY (SERIAL)	
);

-- RRCU_STG_DEV.KEYSTONE_CORE.T_KS_LR_DEBT_RATIO_STG definition

create or replace TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_LR_DEBT_RATIO_STG_CF (
	LRDR_REC_KEY BIGINT,-- REPRESENT POINTER BACK TO DIM
	SOURCEHASH1 VARCHAR(32),  -- TYPE1 SOURCE HASHING
	SOURCEHASH2 VARCHAR(32),	-- TYPE2 SOURCE HASHING
	ISTYPE1	INT,  -- REPRESENTS TYPE 1
	ISTYPE2 INT,  -- REPRESENTS TYPE 2
	ISNEW INT, -- INDICATION FOR NEW RECORD	
	SERIAL NUMBER(19,0),
	PARENT_SERIAL NUMBER(19,0),
	ORDINAL NUMBER(19,0),
	LAST_FM_DATE DATE,
	TYPE_SERIAL NUMBER(19,0),
	RATIO NUMBER(11,5),
	PRIMARY KEY (SERIAL)	
);

-- RRCU_STG_DEV.KEYSTONE_CORE.T_KS_CU_LOANPROMOCODE_STG definition

create or replace TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_CU_LOANPROMOCODE_STG_CF (
	LNPC_REC_KEY BIGINT,-- REPRESENT POINTER BACK TO DIM
	SOURCEHASH1 VARCHAR(32),  -- TYPE1 SOURCE HASHING
	SOURCEHASH2 VARCHAR(32),	-- TYPE2 SOURCE HASHING
	ISTYPE1	INT,  -- REPRESENTS TYPE 1
	ISTYPE2 INT,  -- REPRESENTS TYPE 2
	ISNEW INT, -- INDICATION FOR NEW RECORD	
	SERIAL NUMBER(19,0),
	PARENT_SERIAL NUMBER(19,0),
	ORDINAL NUMBER(19,0),
	LAST_FM_DATE DATE,
	PROMOCODE VARCHAR(40),
	PRIMARY KEY (SERIAL)	
);

-- RRCU_STG_DEV.KEYSTONE_CORE.T_KS_CU_SHAREPROMOCODE_STG definition

create or replace TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_CU_SHAREPROMOCODE_STG_CF (
	SHPC_REC_KEY BIGINT,-- REPRESENT POINTER BACK TO DIM
	SOURCEHASH1 VARCHAR(32),  -- TYPE1 SOURCE HASHING
	SOURCEHASH2 VARCHAR(32),	-- TYPE2 SOURCE HASHING
	ISTYPE1	INT,  -- REPRESENTS TYPE 1
	ISTYPE2 INT,  -- REPRESENTS TYPE 2
	ISNEW INT, -- INDICATION FOR NEW RECORD	
	SERIAL NUMBER(19,0),
	PARENT_SERIAL NUMBER(19,0),
	ORDINAL NUMBER(19,0),
	LAST_FM_DATE DATE,
	SHARE_PROMOCODE VARCHAR(40),
	PRIMARY KEY (SERIAL)
);