


select to_char(to_binary(sha1('214163915155286001'), 'hex'), 'base64') as Result;


SELECT MD5(SERIAL),
--HASH('SHA1', IFNULL(CAST(SERIAL AS VARCHAR), 'UKNOWN' + '|' + ))
 MD5(CAST(SERIAL AS VARCHAR) + '|' + CAST(HOUSEHOLD_PERSON_SERIAL AS VARCHAR) ) 
FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_PERSON_STG;


SELECT md5('Snowflake');




--SERIAL, HOUSEHOLD_PERSON_SERIAL, 
--NAICS_SERIAL, RELATIONSHIP_SERIAL, TAX_PERSON_SERIAL, 
--TAX_STATE_SERIAL, TYPE_SERIAL, ACCESS_RESTRICTION,
--BACKUP_WITHHOLD, BIRTH_DATE, CATEGORY, CHECK_HOLD_LEVEL_SERIAL, 
--CTR_EXEMPTION, CTR_EXEMPTION_REVIEW_DATE, DEATH_DATE, DEMOGRAPHICS_FURNISHED, 
--TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, NICKNAME, SUFFIX, GENDER, HOUSEHOLD_CATEGORY, 
--HOUSEHOLD_REASSIGNMENT, IRS_FORM_W8_EXPIRATION_DATE, IRS_FORM_W9_RECEIVED_DATE, 
--MARKETING_OPTION, NOTE_RESTRICTION, OFAC_LAST_CHECK_DATE, OFAC_RESTRICTION, 
--OWNERSHIP_CHANGE_DATE, RELATIONSHIP_OVR_EFF_DATE, RELATIONSHIP_OVR_EXP_DATE, 
--RELATIONSHIP_OVR_SERIAL, ROW_CHANGE_TIMESTAMP, TAX_COUNTRY_CODE, TAX_REPORTING, LAST_FM_DATE