--==================================================================================================
--Author: Farr, C
--Create Date:	2024-03-05  	
--Object Name:	sp_LOAD_T_AC_NOTE_STG
--Description:  Loading Account Note Data
--***********************************************************************************************************************
--Date			Trello#					ChangedBy						Description 
------------------------------------------------------------------------------------------------------------------------


CREATE OR REPLACE PROCEDURE RRCU_STG_DEV.KEYSTONE_CORE.sp_LOAD_T_AC_NOTE_STG ()
RETURNS VARCHAR NOT NULL
LANGUAGE SQL

AS
$$

BEGIN 
	
	TRUNCATE TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_AC_NOTE_STG_CF;
	
	-- REMOVE PK	
	ALTER TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_AC_NOTE_STG_CF DROP PRIMARY KEY;		

	-- Populate STAGING WITH CTE DATA
	INSERT INTO RRCU_STG_DEV.KEYSTONE_CORE.T_KS_AC_NOTE_STG_CF
	(
	SERIAL,
	SOURCEHASH2,
	PARENT_SERIAL,
	ORDINAL,
	LAST_FM_DATE,
	TYPE_SERIAL,
	PLACEMENT_DATE,
	PLACEMENT_TIME,
	PLACEMENT_USER_SERIAL,
	EXPIRATION_DATE,
	EXPLANATION
	)
	
	WITH CTE AS

	(	
	SELECT 
	SERIAL,
	MD5(TO_VARCHAR(ARRAY_CONSTRUCT(*))) AS SourceHash2,  -- SOURCE HASH	
	PARENT_SERIAL, -- NATURAL KEY TO ACCOUNT
	ORDINAL, -- MAX Ordinal Note.... Do NOT USE - USE CURRENT NOTE CURR_IND
	CASE WHEN LAST_FM_DATE IS NULL THEN PLACEMENT_DATE ELSE LAST_FM_DATE END AS LAST_FM_DATE,
	TYPE_SERIAL, -- NATURAL KEY TO NOTE TYPE
	PLACEMENT_DATE,
	PLACEMENT_TIME,
	PLACEMENT_USER_SERIAL,  --NATURAL KEY TO USER
	EXPIRATION_DATE,  -- EXPIRED NOTE
	EXPLANATION, -- THIS IS THE NOTE DESCRIPTION... 
	ROW_NUMBER() OVER (PARTITION BY SERIAL ORDER BY SERIAL) AS rn -- helps identify mutliple serial number dupes		
	FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_AC_NOTE_STG
	)


	SELECT SERIAL, SOURCEHASH2, PARENT_SERIAL, ORDINAL, LAST_FM_DATE, TYPE_SERIAL, PLACEMENT_DATE, PLACEMENT_TIME,
	PLACEMENT_USER_SERIAL, EXPIRATION_DATE, EXPLANATION
	FROM CTE
	WHERE rn = 1;

	-- DUPE CHECK / DELETE 
	DELETE FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_AC_NOTE_STG_CF USING (
    	WITH CTE_DUP AS
    	(
    	SELECT SERIAL,
	 	ROW_NUMBER () OVER ( PARTITION BY SERIAL ORDER BY SERIAL) AS RN
	 	FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_AC_NOTE_STG_CF
    	)
        SELECT SERIAL, RN FROM CTE_DUP
        ) AS CTE_RESULT
	WHERE CTE_RESULT.RN > 1;

	-- ADD PRIMARY KEY BACK

	ALTER TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_AC_NOTE_STG_CF ADD PRIMARY KEY (SERIAL);

	-- Expiration for Person Business Rules Expiration_Date ONLY

	UPDATE RRCU_DW_DEV.DW.T_KS_AC_NOTE_DW_CF
	SET ACNOTE_CURR_IND = 0,
	ACNOTE_EXP_DT = CURRENT_DATE
	WHERE ACNOTE_EXPIRATION_DATE <= CURRENT_DATE
	AND ACNOTE_EXP_DT IS NULL;

	--UPDATE RRCU_DW_DEV.DW.T_KS_AC_NOTE_DW_CF
	--SET ACNOTE_CURR_IND = 0
	--, ACNOTE_EXP_DT = CURRENT_DATE
	--WHERE ACNOTE_EXPIRATION_DATE IS NOT NULL
	--AND ACNOTE_EXP_DT IS NULL;

	-- Expiration for records not coming back into resultset
	UPDATE RRCU_DW_DEV.DW.T_KS_AC_NOTE_DW_CF
	SET ACNOTE_CURR_IND = 0
	, ACNOTE_EXP_DT = CURRENT_DATE
	WHERE ACNOTE_CURR_IND = 1
	AND ACNOTE_SERIAL NOT IN (SELECT SERIAL FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_AC_NOTE_STG_CF);

	DROP TABLE IF EXISTS RRCU_STG_DEV.KEYSTONE_CORE.Update_STG;

	CREATE TEMPORARY TABLE RRCU_STG_DEV.KEYSTONE_CORE.Update_STG(
	ACNOTE_REC_KEY BIGINT,
	STG_SOURCEHASH2 VARCHAR(32),
	NEW_SOURCEHASH2 VARCHAR(32),
	IS_TYPE2 INT,  -- REPRESENTS TYPE 2
	IS_NEW INT -- INDICATION FOR NEW RECORD TYPE 2
	);


	INSERT INTO RRCU_STG_DEV.KEYSTONE_CORE.Update_STG (
	ACNOTE_REC_KEY,
	STG_SOURCEHASH2,
	NEW_SOURCEHASH2,
	IS_NEW,
	IS_TYPE2	
	)
	
	WITH CTE_COMPARE AS
	(
	SELECT dim.ACNOTE_REC_KEY ,  dim.ACNOTE_SOURCEHASH2, stg.sourcehash2,
	CASE WHEN dim.ACNOTE_REC_KEY IS NULL THEN 1 ELSE 0 END CASE,
	CASE WHEN dim.ACNOTE_REC_KEY IS NOT NULL AND stg.SOURCEHASH2 <> dim.ACNOTE_SOURCEHASH2 THEN 1 ELSE 0 END CASE
	FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_AC_NOTE_STG_CF stg
	LEFT OUTER JOIN RRCU_DW_DEV.DW.T_KS_AC_NOTE_DW_CF dim ON dim.ACNOTE_SERIAL = stg.SERIAL AND dim.ACNOTE_CURR_IND  = 1
	)
	SELECT *
	FROM CTE_COMPARE;

	--SELECT * FROM RRCU_STG_DEV.KEYSTONE_CORE.Update_STG;

	UPDATE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_AC_NOTE_STG_CF a
	SET ACNOTE_REC_KEY = b.ACNOTE_REC_KEY,
	ISNEW = b.IS_NEW,
	ISTYPE2 = b.IS_TYPE2
	FROM (SELECT ACNOTE_REC_KEY, IS_NEW, IS_TYPE2, NEW_SOURCEHASH2 FROM RRCU_STG_DEV.KEYSTONE_CORE.Update_STG) b
	WHERE a.SOURCEHASH2 = b.NEW_SOURCEHASH2 AND a.ACNOTE_REC_KEY IS NULL;

	--SELECT isnew, count(*)
	--FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_AC_NOTE_STG_CF
	--WHERE isnew = 1
	--GROUP BY isnew
	--WHERE SOURCEHASH2 IN (SELECT NEW_SOURCEHASH2 FROM RRCU_STG_DEV.KEYSTONE_CORE.Update_STG);

   -- Expiration for records type 2
	
   UPDATE RRCU_DW_DEV.DW.T_KS_AC_NOTE_DW_CF
	SET ACNOTE_CURR_IND = 0
	, ACNOTE_EXP_DT = CURRENT_DATE
	WHERE ACNOTE_CURR_IND = 1
	AND ACNOTE_SERIAL IN (SELECT SERIAL FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_AC_NOTE_STG_CF WHERE ISTYPE2 = 1); 
	

	INSERT INTO RRCU_DW_DEV.DW.T_KS_AC_NOTE_DW_CF
	(
	ACNOTE_SERIAL,
	ACNOTE_CURR_IND,
	ACNOTE_EFF_DT,
	ACNOTE_EXP_DT,
	--ACNOTE_MOD_DT,
	ACNOTE_SOURCEHASH2,
	ACNOTE_PARENT_SERIAL,
	ACNOTE_ORDINAL,
	ACNOTE_LAST_FM_DATE,
	ACNOTE_TYPE_SERIAL,
	ACNOTE_PLACEMENT_DATE,
	ACNOTE_PLACEMENT_TIME,
	ACNOTE_PLACEMENT_USER_SERIAL,
	ACNOTE_EXPIRATION_DATE,
	ACNOTE_EXPLANATION
	)
	
	SELECT 
	stg.SERIAL,
	1,
	CURRENT_DATE,
	NULL,
	stg.SOURCEHASH2,
	stg.PARENT_SERIAL,
	stg.ORDINAL, 
	stg.LAST_FM_DATE,
	stg.TYPE_SERIAL,
	stg.PLACEMENT_DATE,
	stg.PLACEMENT_TIME,
	stg.PLACEMENT_USER_SERIAL,
	stg.EXPIRATION_DATE,
	stg.EXPLANATION
	FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_AC_NOTE_STG_CF stg
		WHERE ISNEW = 1 OR ISTYPE2 = 1;

	-- Business rules around death date for current records
	UPDATE RRCU_DW_DEV.DW.T_KS_AC_NOTE_DW_CF
	SET ACNOTE_CURR_IND = 0
	, ACNOTE_EXP_DT = CURRENT_DATE
	WHERE ACNOTE_EXPIRATION_DATE <= CURRENT_DATE
	AND ACNOTE_CURR_IND = 1;



END;
$$
;







	