/*
--==================================================================================================
--Author: Farr, C
--Create Date:	2024-04-03  	
--Object Name:	sp_LOAD_T_RENTAL_STG
--Description:  Loading Share Data
--***********************************************************************************************************************
--Date			Trello#					ChangedBy						Description 
------------------------------------------------------------------------------------------------------------------------
*/

CREATE OR REPLACE PROCEDURE RRCU_STG_DEV.KEYSTONE_CORE.sp_LOAD_T_RENTAL_STG()
RETURNS VARCHAR NOT NULL
LANGUAGE SQL

AS
$$

BEGIN 
	
	TRUNCATE TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_RENTAL_STG_CF;
	
	-- REMOVE PK	
	ALTER TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_RENTAL_STG_CF DROP PRIMARY KEY;
	
	-- Populate STAGING WITH CTE DATA
	INSERT INTO RRCU_STG_DEV.KEYSTONE_CORE.T_KS_RENTAL_STG_CF
	(
	SERIAL,
	SOURCEHASH2,
	LAST_FM_DATE, 
	DESCRIPTION, 
	TYPE_SERIAL, 
	BRANCH_SERIAL, 
	STATUS, 
	STATUS_DATE, 
	STATUS_COMMENT, 
	AVAILABLE_DATE, 
	RENTAL_START_DATE, 
	LAST_FEE_AMOUNT, 
	LAST_FEE_DATE, 
	NEXT_FEE_DATE, 
	NSF_FEE_DATE, 
	SHARE_SERIAL, 
	LOAN_SERIAL,
	KEY_COUNT, 
	SERIAL_NUMBER, 
	ASSET_NUMBER, 
	ADDITIONAL_INFORMATION
	)
	
	WITH CTE AS

	(	
	SELECT 
	SERIAL,
	MD5(TO_VARCHAR(ARRAY_CONSTRUCT(*))) AS SourceHash2,  -- SOURCE HASH	
	LAST_FM_DATE, 
	DESCRIPTION, 
	TYPE_SERIAL, 
	BRANCH_SERIAL, 
	STATUS, 
	STATUS_DATE, 
	STATUS_COMMENT, 
	AVAILABLE_DATE, 
	RENTAL_START_DATE, 
	LAST_FEE_AMOUNT, 
	LAST_FEE_DATE, 
	NEXT_FEE_DATE, 
	NSF_FEE_DATE, 
	SHARE_SERIAL, 
	LOAN_SERIAL, 
	KEY_COUNT, 
	SERIAL_NUMBER, 
	ASSET_NUMBER, 
	ADDITIONAL_INFORMATION,
	ROW_NUMBER() OVER (PARTITION BY SERIAL ORDER BY SERIAL) AS rn -- helps identify mutliple serial number dupes		
	FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_RENTAL_STG
	)

	SELECT SERIAL, SOURCEHASH2, LAST_FM_DATE, DESCRIPTION, TYPE_SERIAL, BRANCH_SERIAL, STATUS, STATUS_DATE, STATUS_COMMENT, AVAILABLE_DATE, 
	RENTAL_START_DATE, LAST_FEE_AMOUNT, LAST_FEE_DATE, NEXT_FEE_DATE, NSF_FEE_DATE, SHARE_SERIAL, LOAN_SERIAL, KEY_COUNT, SERIAL_NUMBER, 
	ASSET_NUMBER, ADDITIONAL_INFORMATION
	FROM CTE
	WHERE rn = 1;

	-- DUPE CHECK / DELETE 
	DELETE FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_RENTAL_STG_CF USING (
    	WITH CTE_DUP AS
    	(
    	SELECT SERIAL,
	 	ROW_NUMBER () OVER ( PARTITION BY SERIAL ORDER BY SERIAL) AS RN
	 	FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_RENTAL_STG_CF
    	)
        SELECT SERIAL, RN FROM CTE_DUP
        ) AS CTE_RESULT
	WHERE CTE_RESULT.RN > 1;
	

	-- ADD PRIMARY KEY BACK

	ALTER TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_RENTAL_STG_CF ADD PRIMARY KEY (SERIAL);

	-- Expiration for records not coming back into resultset
	UPDATE RRCU_DW_DEV.DW.T_KS_RENTAL_DW_CF
	SET RENT_CURR_IND = 0
	, RENT_EXP_DT = CURRENT_DATE
	WHERE RENT_CURR_IND = 1
	AND RENT_SERIAL NOT IN (SELECT SERIAL FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_RENTAL_STG_CF);

	DROP TABLE IF EXISTS RRCU_STG_DEV.KEYSTONE_CORE.Update_STG;

	CREATE TEMPORARY TABLE RRCU_STG_DEV.KEYSTONE_CORE.Update_STG(
	RENT_REC_KEY BIGINT,
	STG_SOURCEHASH2 VARCHAR(32),
	NEW_SOURCEHASH2 VARCHAR(32),
	IS_TYPE2 INT,  -- REPRESENTS TYPE 2
	IS_NEW INT -- INDICATION FOR NEW RECORD TYPE 2
	);


	INSERT INTO RRCU_STG_DEV.KEYSTONE_CORE.Update_STG (
	RENT_REC_KEY,
	STG_SOURCEHASH2,
	NEW_SOURCEHASH2,
	IS_NEW,
	IS_TYPE2	
	)
	
	WITH CTE_COMPARE AS
	(
	SELECT dim.RENT_REC_KEY ,  dim.RENT_SOURCEHASH2, stg.sourcehash2,
	CASE WHEN dim.RENT_REC_KEY IS NULL THEN 1 ELSE 0 END CASE,
	CASE WHEN dim.RENT_REC_KEY IS NOT NULL AND stg.SOURCEHASH2 <> dim.RENT_SOURCEHASH2 THEN 1 ELSE 0 END CASE
	FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_RENTAL_STG_CF stg
	LEFT OUTER JOIN RRCU_DW_DEV.DW.T_KS_RENTAL_DW_CF dim ON dim.RENT_SERIAL = stg.SERIAL AND dim.RENT_CURR_IND  = 1
	)
	SELECT *
	FROM CTE_COMPARE;

	UPDATE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_RENTAL_STG_CF a
	SET RENT_REC_KEY = b.RENT_REC_KEY,
	ISNEW = b.IS_NEW,
	ISTYPE2 = b.IS_TYPE2
	FROM (SELECT RENT_REC_KEY, IS_NEW, IS_TYPE2, NEW_SOURCEHASH2 FROM RRCU_STG_DEV.KEYSTONE_CORE.Update_STG) b
	WHERE a.SOURCEHASH2 = b.NEW_SOURCEHASH2 AND a.RENT_REC_KEY IS NULL;

	-- Expiration for records type 2
	
    UPDATE RRCU_DW_DEV.DW.T_KS_RENTAL_DW_CF
	SET RENT_CURR_IND = 0
	, RENT_EXP_DT = CURRENT_DATE
	WHERE RENT_CURR_IND = 1
	AND RENT_SERIAL IN (SELECT SERIAL FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_RENTAL_STG_CF WHERE ISTYPE2 = 1); 

	INSERT INTO RRCU_DW_DEV.DW.T_KS_RENTAL_DW_CF
	(
	RENT_SERIAL, 
	RENT_CURR_IND, 
	RENT_EFF_DT, 
	RENT_EXP_DT, 
	--RENT_MOD_DT, 
	RENT_SOURCEHASH2, 
	RENT_LAST_FM_DATE, 
	RENT_DESCRIPTION, 
	RENT_TYPE_SERIAL, 
	RENT_BRANCH_SERIAL, 
	RENT_STATUS, 
	RENT_STATUS_DATE, 
	RENT_STATUS_COMMENT, 
	RENT_AVAILABLE_DATE, 
	RENT_RENTAL_START_DATE, 
	RENT_LAST_FEE_AMOUNT, 
	RENT_LAST_FEE_DATE, 
	RENT_NEXT_FEE_DATE, 
	RENT_NSF_FEE_DATE, 
	RENT_SHARE_SERIAL, 
	RENT_LOAN_SERIAL, 
	RENT_KEY_COUNT, 
	RENT_SERIAL_NUMBER, 
	RENT_ASSET_NUMBER, 
	RENT_ADDITIONAL_INFORMATION, 
	DW_LOAD_DT
	)

	SELECT 
	stg.SERIAL,
	1,
	CURRENT_DATE,
	NULL,
	stg.SOURCEHASH2,
	stg.LAST_FM_DATE, 
	stg.DESCRIPTION, 
	stg.TYPE_SERIAL, 
	stg.BRANCH_SERIAL, 
	stg.STATUS, 
	stg.STATUS_DATE, 
	stg.STATUS_COMMENT, 
	stg.AVAILABLE_DATE, 
	stg.RENTAL_START_DATE, 
	stg.LAST_FEE_AMOUNT, 
	stg.LAST_FEE_DATE, 
	stg.NEXT_FEE_DATE, 
	stg.NSF_FEE_DATE, 
	stg.SHARE_SERIAL, 
	stg.LOAN_SERIAL, 
	stg.KEY_COUNT, 
	stg.SERIAL_NUMBER, 
	stg.ASSET_NUMBER, 
	stg.ADDITIONAL_INFORMATION,
	CURRENT_DATE
	FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_RENTAL_STG_CF stg
		WHERE ISNEW = 1 OR ISTYPE2 = 1;
	
	UPDATE RRCU_DW_DEV.DW.T_KS_RENTAL_DW_CF
	SET RENT_CURR_IND = 0
	, RENT_EXP_DT = CURRENT_DATE
	WHERE RENT_STATUS <> 'R';

	UPDATE RRCU_DW_DEV.DW.T_KS_RENTAL_DW_CF
	SET RENT_CURR_IND = 1
	, RENT_EXP_DT = NULL
	WHERE RENT_STATUS = 'R';


END;
$$
;