/*
--==================================================================================================
--Author: Farr, C
--Create Date:	2024-04-02  	
--Object Name:	sp_LOAD_T_RENTAL_TYPE_STG
--Description:  Loading Rental Type Data
--***********************************************************************************************************************
--Date			Trello#					ChangedBy						Description 
------------------------------------------------------------------------------------------------------------------------
*/

CREATE OR REPLACE PROCEDURE RRCU_STG_DEV.KEYSTONE_CORE.sp_LOAD_T_RENTAL_TYPE_STG()
RETURNS VARCHAR NOT NULL
LANGUAGE SQL

AS
$$

BEGIN 
	
	TRUNCATE TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_RENTAL_TYPE_STG_CF;
	
	-- REMOVE PK	
	ALTER TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_RENTAL_TYPE_STG_CF DROP PRIMARY KEY;
	
	-- Populate STAGING WITH CTE DATA
	INSERT INTO RRCU_STG_DEV.KEYSTONE_CORE.T_KS_RENTAL_TYPE_STG_CF
	(
	SERIAL,
	SOURCEHASH2,
	LAST_FM_DATE, 
	DESCRIPTION, 
	STATUS, 
	CODE,
	CATEGORY, 
	TERM_OPTION, 
	NEW_RENTAL_PRORATE_OPTION, 
	SURRENDER_PRORATE_OPTION, 
	FREQUENCY, 
	FREQUENCY_DAY_1, 
	FREQUENCY_DAY_2, 
	NEXT_PERIOD_DATE, 
	FEE_SERIAL, 
	FEE_POSTING_POLICY_OPTION, 
	ACCESS_FORM_TYPE_SERIAL
	)
	
	WITH CTE AS

	(	
	SELECT 
	SERIAL,
	MD5(TO_VARCHAR(ARRAY_CONSTRUCT(*))) AS SourceHash2,  -- SOURCE HASH	
	LAST_FM_DATE, 
	DESCRIPTION, 
	STATUS, 
	CODE, 
	CATEGORY, 
	TERM_OPTION, 
	NEW_RENTAL_PRORATE_OPTION, 
	SURRENDER_PRORATE_OPTION, 
	FREQUENCY, 
	FREQUENCY_DAY_1, 
	FREQUENCY_DAY_2, 
	NEXT_PERIOD_DATE, 
	FEE_SERIAL, 
	FEE_POSTING_POLICY_OPTION, 
	ACCESS_FORM_TYPE_SERIAL,
	ROW_NUMBER() OVER (PARTITION BY SERIAL ORDER BY SERIAL) AS rn -- helps identify mutliple serial number dupes		
	FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_RENTAL_TYPE_STG
	)

	SELECT SERIAL, SOURCEHASH2, LAST_FM_DATE, DESCRIPTION, STATUS, CODE, CATEGORY, TERM_OPTION, NEW_RENTAL_PRORATE_OPTION, SURRENDER_PRORATE_OPTION, 
	FREQUENCY, FREQUENCY_DAY_1, FREQUENCY_DAY_2, NEXT_PERIOD_DATE, FEE_SERIAL, FEE_POSTING_POLICY_OPTION, ACCESS_FORM_TYPE_SERIAL
	FROM CTE
	WHERE rn = 1;

	-- DUPE CHECK / DELETE 
	DELETE FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_RENTAL_TYPE_STG_CF USING (
    	WITH CTE_DUP AS
    	(
    	SELECT SERIAL,
	 	ROW_NUMBER () OVER ( PARTITION BY SERIAL ORDER BY SERIAL) AS RN
	 	FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_RENTAL_TYPE_STG_CF
    	)
        SELECT SERIAL, RN FROM CTE_DUP
        ) AS CTE_RESULT
	WHERE CTE_RESULT.RN > 1;

	-- ADD PRIMARY KEY BACK

	ALTER TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_RENTAL_TYPE_STG_CF ADD PRIMARY KEY (SERIAL);

	-- Expiration for records not coming back into resultset
	UPDATE RRCU_DW_DEV.DW.T_KS_RENTAL_TYPE_DW_CF
	SET RNTYP_CURR_IND = 0
	, RNTYP_EXP_DT = CURRENT_DATE
	WHERE RNTYP_CURR_IND = 1
	AND RNTYP_SERIAL NOT IN (SELECT SERIAL FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_RENTAL_TYPE_STG_CF);

	DROP TABLE IF EXISTS RRCU_STG_DEV.KEYSTONE_CORE.Update_STG;

	CREATE TEMPORARY TABLE RRCU_STG_DEV.KEYSTONE_CORE.Update_STG(
	RNTYP_REC_KEY BIGINT,
	STG_SOURCEHASH2 VARCHAR(32),
	NEW_SOURCEHASH2 VARCHAR(32),
	IS_TYPE2 INT,  -- REPRESENTS TYPE 2
	IS_NEW INT -- INDICATION FOR NEW RECORD TYPE 2
	);


	INSERT INTO RRCU_STG_DEV.KEYSTONE_CORE.Update_STG (
	RNTYP_REC_KEY,
	STG_SOURCEHASH2,
	NEW_SOURCEHASH2,
	IS_NEW,
	IS_TYPE2	
	)
	
	WITH CTE_COMPARE AS
	(
	SELECT dim.RNTYP_REC_KEY ,  dim.RNTYP_SOURCEHASH2, stg.sourcehash2,
	CASE WHEN dim.RNTYP_REC_KEY IS NULL THEN 1 ELSE 0 END CASE,
	CASE WHEN dim.RNTYP_REC_KEY IS NOT NULL AND stg.SOURCEHASH2 <> dim.RNTYP_SOURCEHASH2 THEN 1 ELSE 0 END CASE
	FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_RENTAL_TYPE_STG_CF stg
	LEFT OUTER JOIN RRCU_DW_DEV.DW.T_KS_RENTAL_TYPE_DW_CF dim ON dim.RNTYP_SERIAL = stg.SERIAL AND dim.RNTYP_CURR_IND  = 1
	)
	SELECT *
	FROM CTE_COMPARE;

	UPDATE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_RENTAL_TYPE_STG_CF a
	SET RNTYP_REC_KEY = b.RNTYP_REC_KEY,
	ISNEW = b.IS_NEW,
	ISTYPE2 = b.IS_TYPE2
	FROM (SELECT RNTYP_REC_KEY, IS_NEW, IS_TYPE2, NEW_SOURCEHASH2 FROM RRCU_STG_DEV.KEYSTONE_CORE.Update_STG) b
	WHERE a.SOURCEHASH2 = b.NEW_SOURCEHASH2 AND a.RNTYP_REC_KEY IS NULL;

	-- Expiration for records type 2
	
   UPDATE RRCU_DW_DEV.DW.T_KS_RENTAL_TYPE_DW_CF
	SET RNTYP_CURR_IND = 0
	, RNTYP_EXP_DT = CURRENT_DATE
	WHERE RNTYP_CURR_IND = 1
	AND RNTYP_SERIAL IN (SELECT SERIAL FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_RENTAL_TYPE_STG_CF WHERE ISTYPE2 = 1);

	INSERT INTO RRCU_DW_DEV.DW.T_KS_RENTAL_TYPE_DW_CF
	(
	RNTYP_SERIAL, 
	RNTYP_CURR_IND, 
	RNTYP_EFF_DT, 
	RNTYP_EXP_DT, 
	--RNTYP_MOD_DT, 
	RNTYP_SOURCEHASH2, 
	RNTYP_LAST_FM_DATE, 
	RNTYP_DESCRIPTION, 
	RNTYP_STATUS, 
	RNTYP_CODE, 
	RNTYP_CATEGORY, 
	RNTYP_TERM_OPTION, 
	RNTYP_NEW_RENTAL_PRORATE_OPTION, 
	RNTYP_SURRENDER_PRORATE_OPTION, 
	RNTYP_FREQUENCY, 
	RNTYP_FREQUENCY_DAY_1, 
	RNTYP_FREQUENCY_DAY_2, 
	RNTYP_NEXT_PERIOD_DATE, 
	RNTYP_FEE_SERIAL, 
	RNTYP_FEE_POSTING_POLICY_OPTION, 
	RNTYP_ACCESS_FORM_TYPE_SERIAL, 
	DW_LOAD_DT
	)
	
	SELECT 
	stg.SERIAL,
	1,
	CURRENT_DATE,
	NULL,
	stg.SOURCEHASH2,
	stg.LAST_FM_DATE, 
	stg.DESCRIPTION, 
	stg.STATUS, 
	stg.CODE, 
	stg.CATEGORY, 
	stg.TERM_OPTION, 
	stg.NEW_RENTAL_PRORATE_OPTION, 
	stg.SURRENDER_PRORATE_OPTION, 
	stg.FREQUENCY, 
	stg.FREQUENCY_DAY_1, 
	stg.FREQUENCY_DAY_2, 
	stg.NEXT_PERIOD_DATE, 
	stg.FEE_SERIAL, 
	stg.FEE_POSTING_POLICY_OPTION, 
	stg.ACCESS_FORM_TYPE_SERIAL,
	CURRENT_DATE
	FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_RENTAL_TYPE_STG_CF stg
		WHERE ISNEW = 1 OR ISTYPE2 = 1;
	
	-- Business rules status for current records
	UPDATE RRCU_DW_DEV.DW.T_KS_RENTAL_TYPE_DW_CF
	SET RNTYP_CURR_IND = 0,
	RNTYP_EXP_DT = CURRENT_DATE
	WHERE RNTYP_STATUS = 'C'
	AND RNTYP_EXP_DT IS NULL;

END;
$$
;


