/*
--==================================================================================================
--Author: Farr, C
--Create Date:	2024-04-03  	
--Object Name:	sp_LOAD_T_SHARE_STG
--Description:  Loading Share Data
--***********************************************************************************************************************
--Date			Trello#					ChangedBy						Description 
------------------------------------------------------------------------------------------------------------------------
*/

CREATE OR REPLACE PROCEDURE RRCU_STG_DEV.KEYSTONE_CORE.sp_LOAD_T_SHARE_STG()
RETURNS VARCHAR NOT NULL
LANGUAGE SQL

AS
$$

BEGIN 
	
	TRUNCATE TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_SHARE_STG_CF;
	
	-- REMOVE PK	
	ALTER TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_SHARE_STG_CF DROP PRIMARY KEY;

	-- Populate STAGING WITH CTE DATA
	INSERT INTO RRCU_STG_DEV.KEYSTONE_CORE.T_KS_SHARE_STG_CF
	(
	SERIAL,
	SOURCEHASH2,
	PARENT_SERIAL, 
	STORED_ACCESS_KEY,
	ORDINAL, 
	LAST_FM_DATE, 
	ID, 
	DESCRIPTION, 
	TYPE_SERIAL, 
	PROCESSING, 
	BRANCH_SERIAL, 
	OPEN_DATE, 
	OPENED_BY_USER_SERIAL, 
	CLOSE_DATE, 
	CLOSE_REASON_SERIAL, 
	CHARGE_OFF_TYPE_SERIAL, 
	CHARGE_OFF_DATE, 
	CHARGE_OFF_AMOUNT, 
	COLLECTION_STATUS, 
	COLLECTION_HANDLING, 
	COLLECTION_NOTICE_COUNT, 
	COLLECTION_NOTICE_DATE, 
	CRED_REP_PRIMARY_ECOA_CODE, 
	CRED_REP_PRIMARY_CONS_INFO_IND, 
	CRED_REP_BANKRUPTCY_DATE, 
	CRED_REP_ACCOUNT_TYPE, 
	CRED_REP_SPEC_COMM_CODE, 
	CRED_REP_COMP_COND_CODE, 
	CRED_REP_FIRST_DQ_DATE,
	CRED_REP_ACCOUNT_STATUS, 
	CRED_REP_LAST_DATE, 
	SHARED_BRANCH_OPTION, 
	NOTE_RESTRICTION, 
	DEPOSIT_RESTRICTION, 
	WITHDRAWAL_RESTRICTION, 
	MONETARY_PURGE_DATE, 
	LAST_MONETARY_DATE, 
	LAST_ACTIVITY_DATE, 
	BALANCE, 
	MINIMUM_BALANCE, 
	MINIMUM_DEPOSIT, 
	MINIMUM_WITHDRAWAL, 
	SWEEP_OPTION, 
	SWEEP_TARGET_BALANCE, 
	SWEEP_MINIMUM_BALANCE, 
	SWEEP_MAXIMUM_BALANCE, 
	COURTESY_PAY_LIMIT, 
	COURTESY_PAY_RESTRICT_SERIAL, 
	COURTESY_PAY_ATM_DEBIT, 
	COURTESY_PAY_ATM_DEBIT_CH_DATE, 
	COURTESY_PAY_OTHER, 
	COURTESY_PAY_OTHER_CH_DATE, 
	POSITIVE_PAY_OPTION, 
	CK_HLD_NEXT_DAY_AVAIL_AMOUNT, 
	OPENING_BALANCE, 
	ORIGINAL_AMOUNT, 
	ORIGINAL_DATE, 
	CERT_NUMBER, 
	CERT_PEN_CALCULATION_SERIAL, 
	CERT_PEN_WAIVE_COUNT, 
	CERT_PEN_WAIVE_LAST_DATE, 
	CERT_DIVIDENDS_AVAILABLE, 
	CERT_OID_YIELD_TO_MATURITY, 
	CERT_OID_BALANCE, 
	CERT_BUMP_COUNT, 
	CERT_BUMP_LAST_DATE, 
	MATURITY_POSTING, 
	MATURITY_FREQUENCY, 
	MATURITY_PERIOD, 
	MATURITY_DATE,
	MATURITY_LAST_DATE, 
	MATURITY_RENEW_DEFAULTS_SERIAL, 
	MAIL_PERSON_ADDR_LINK_SERIAL, 
	STMT_MAIL_GROUP_SERIAL, 
	STMT_CUTOFF_GROUP_SERIAL, 
	STMT_CUTOFF_LAST_DATE, 
	STMT_CUTOFF_LAST_TRAN_SERIAL, 
	STMT_CUTOFF_PRIOR_DATE, 
	STMT_CUTOFF_PRIOR_TRAN_SERIAL, 
	STMT_REG_E_COUNT, 
	ANALYSIS_CATEGORY, 
	ANALYSIS_SHARE_SERIAL, 
	TAX_PERSON_SERIAL, 
	TAX_PLAN_CATEGORY, 
	TAX_PLAN_SERIAL, 
	DIVIDEND_CALCULATION_SERIAL, 
	DIVIDEND_POSTING, 
	DIVIDEND_CUSTOM_RATE, 
	DIVIDEND_LAST_AMOUNT, 
	DIVIDEND_LAST_DATE, 
	DIVIDEND_ACCRUED_DATE, 
	DIVIDEND_ACCRUED_AMOUNT, 
	DIVIDEND_APYE_START_DATE, 
	DIVIDEND_APYE_DAILY_BAL, 
	ACH_DEPOSIT_LAST_AMOUNT,
	ACH_DEPOSIT_LAST_DATE, 
	REG_D_COUNT, 
	REG_D_COUNT_PRIOR, 
	REG_D_PAY, 
	REG_D_PAY_CH_DATE, 
	CRED_REP_PRIMARY_CONS_FIN_DATE	
	)
	
	WITH CTE AS

	(	
	SELECT 
	SERIAL,
	MD5(TO_VARCHAR(ARRAY_CONSTRUCT(*))) AS SourceHash2,  -- SOURCE HASH	
	PARENT_SERIAL, 
	STORED_ACCESS_KEY, 
	ORDINAL, 
	LAST_FM_DATE, 
	ID, 
	DESCRIPTION, 
	TYPE_SERIAL, 
	PROCESSING, 
	BRANCH_SERIAL, 
	OPEN_DATE, 
	OPENED_BY_USER_SERIAL, 
	CLOSE_DATE, -- buisness RULE FOR expried
	CLOSE_REASON_SERIAL, 
	CHARGE_OFF_TYPE_SERIAL,
	CHARGE_OFF_DATE, 
	CHARGE_OFF_AMOUNT, 
	COLLECTION_STATUS, 
	COLLECTION_HANDLING, 
	COLLECTION_NOTICE_COUNT, 
	COLLECTION_NOTICE_DATE, 
	CRED_REP_PRIMARY_ECOA_CODE, 
	CRED_REP_PRIMARY_CONS_INFO_IND, 
	CRED_REP_BANKRUPTCY_DATE, 
	CRED_REP_ACCOUNT_TYPE, 
	CRED_REP_SPEC_COMM_CODE, 
	CRED_REP_COMP_COND_CODE, 
	CRED_REP_FIRST_DQ_DATE,
	CRED_REP_ACCOUNT_STATUS, 
	CRED_REP_LAST_DATE, 
	SHARED_BRANCH_OPTION, 
	NOTE_RESTRICTION, 
	DEPOSIT_RESTRICTION, 
	WITHDRAWAL_RESTRICTION, 
	MONETARY_PURGE_DATE, 
	LAST_MONETARY_DATE, 
	LAST_ACTIVITY_DATE, 
	BALANCE, 
	MINIMUM_BALANCE, 
	MINIMUM_DEPOSIT, 
	MINIMUM_WITHDRAWAL, 
	SWEEP_OPTION, 
	SWEEP_TARGET_BALANCE, 
	SWEEP_MINIMUM_BALANCE, 
	SWEEP_MAXIMUM_BALANCE, 
	COURTESY_PAY_LIMIT, 
	COURTESY_PAY_RESTRICT_SERIAL, 
	COURTESY_PAY_ATM_DEBIT, 
	COURTESY_PAY_ATM_DEBIT_CH_DATE, 
	COURTESY_PAY_OTHER, 
	COURTESY_PAY_OTHER_CH_DATE, 
	POSITIVE_PAY_OPTION, 
	CK_HLD_NEXT_DAY_AVAIL_AMOUNT, 
	OPENING_BALANCE, 
	ORIGINAL_AMOUNT, 
	ORIGINAL_DATE, 
	CERT_NUMBER, 
	CERT_PEN_CALCULATION_SERIAL, 
	CERT_PEN_WAIVE_COUNT, 
	CERT_PEN_WAIVE_LAST_DATE, 
	CERT_DIVIDENDS_AVAILABLE, 
	CERT_OID_YIELD_TO_MATURITY, 
	CERT_OID_BALANCE, 
	CERT_BUMP_COUNT, 
	CERT_BUMP_LAST_DATE, 
	MATURITY_POSTING, 
	MATURITY_FREQUENCY, 
	MATURITY_PERIOD, 
	MATURITY_DATE, -- buisness RULE FOR expried
	MATURITY_LAST_DATE, 
	MATURITY_RENEW_DEFAULTS_SERIAL, 
	MAIL_PERSON_ADDR_LINK_SERIAL, 
	STMT_MAIL_GROUP_SERIAL, 
	STMT_CUTOFF_GROUP_SERIAL, 
	STMT_CUTOFF_LAST_DATE, 
	STMT_CUTOFF_LAST_TRAN_SERIAL, 
	STMT_CUTOFF_PRIOR_DATE, 
	STMT_CUTOFF_PRIOR_TRAN_SERIAL, 
	STMT_REG_E_COUNT, 
	ANALYSIS_CATEGORY, 
	ANALYSIS_SHARE_SERIAL, 
	TAX_PERSON_SERIAL, 
	TAX_PLAN_CATEGORY, 
	TAX_PLAN_SERIAL, 
	DIVIDEND_CALCULATION_SERIAL, 
	DIVIDEND_POSTING, 
	DIVIDEND_CUSTOM_RATE, 
	DIVIDEND_LAST_AMOUNT, 
	DIVIDEND_LAST_DATE, 
	DIVIDEND_ACCRUED_DATE, 
	DIVIDEND_ACCRUED_AMOUNT, 
	DIVIDEND_APYE_START_DATE, 
	DIVIDEND_APYE_DAILY_BAL, 
	ACH_DEPOSIT_LAST_AMOUNT,
	ACH_DEPOSIT_LAST_DATE, 
	REG_D_COUNT,
	REG_D_COUNT_PRIOR, 
	REG_D_PAY, 
	REG_D_PAY_CH_DATE, 
	CRED_REP_PRIMARY_CONS_FIN_DATE,	
	ROW_NUMBER() OVER (PARTITION BY SERIAL ORDER BY SERIAL) AS rn -- helps identify mutliple serial number dupes		
	FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_SHARE_STG
	)

	SELECT SERIAL, SOURCEHASH2,	PARENT_SERIAL, STORED_ACCESS_KEY, ORDINAL, LAST_FM_DATE, ID, DESCRIPTION, TYPE_SERIAL, PROCESSING, BRANCH_SERIAL, OPEN_DATE, OPENED_BY_USER_SERIAL, 
	CLOSE_DATE, CLOSE_REASON_SERIAL, CHARGE_OFF_TYPE_SERIAL, CHARGE_OFF_DATE, CHARGE_OFF_AMOUNT, COLLECTION_STATUS, COLLECTION_HANDLING, COLLECTION_NOTICE_COUNT, COLLECTION_NOTICE_DATE, 
	CRED_REP_PRIMARY_ECOA_CODE, CRED_REP_PRIMARY_CONS_INFO_IND, CRED_REP_BANKRUPTCY_DATE, CRED_REP_ACCOUNT_TYPE, CRED_REP_SPEC_COMM_CODE, CRED_REP_COMP_COND_CODE, CRED_REP_FIRST_DQ_DATE,
	CRED_REP_ACCOUNT_STATUS, CRED_REP_LAST_DATE, SHARED_BRANCH_OPTION, NOTE_RESTRICTION, DEPOSIT_RESTRICTION, WITHDRAWAL_RESTRICTION, MONETARY_PURGE_DATE, LAST_MONETARY_DATE, 
	LAST_ACTIVITY_DATE, BALANCE, MINIMUM_BALANCE, MINIMUM_DEPOSIT, MINIMUM_WITHDRAWAL, SWEEP_OPTION, SWEEP_TARGET_BALANCE, SWEEP_MINIMUM_BALANCE, SWEEP_MAXIMUM_BALANCE, COURTESY_PAY_LIMIT, 
	COURTESY_PAY_RESTRICT_SERIAL, COURTESY_PAY_ATM_DEBIT, COURTESY_PAY_ATM_DEBIT_CH_DATE, COURTESY_PAY_OTHER, COURTESY_PAY_OTHER_CH_DATE, POSITIVE_PAY_OPTION, CK_HLD_NEXT_DAY_AVAIL_AMOUNT, 
	OPENING_BALANCE, ORIGINAL_AMOUNT, ORIGINAL_DATE, CERT_NUMBER, CERT_PEN_CALCULATION_SERIAL, CERT_PEN_WAIVE_COUNT, CERT_PEN_WAIVE_LAST_DATE, CERT_DIVIDENDS_AVAILABLE, CERT_OID_YIELD_TO_MATURITY, 
	CERT_OID_BALANCE, CERT_BUMP_COUNT, CERT_BUMP_LAST_DATE, MATURITY_POSTING, MATURITY_FREQUENCY, MATURITY_PERIOD, MATURITY_DATE,MATURITY_LAST_DATE, MATURITY_RENEW_DEFAULTS_SERIAL, 
	MAIL_PERSON_ADDR_LINK_SERIAL, STMT_MAIL_GROUP_SERIAL, STMT_CUTOFF_GROUP_SERIAL, STMT_CUTOFF_LAST_DATE, STMT_CUTOFF_LAST_TRAN_SERIAL, STMT_CUTOFF_PRIOR_DATE, STMT_CUTOFF_PRIOR_TRAN_SERIAL, 
	STMT_REG_E_COUNT, ANALYSIS_CATEGORY, ANALYSIS_SHARE_SERIAL, TAX_PERSON_SERIAL, TAX_PLAN_CATEGORY, TAX_PLAN_SERIAL, DIVIDEND_CALCULATION_SERIAL, DIVIDEND_POSTING, 
	DIVIDEND_CUSTOM_RATE, DIVIDEND_LAST_AMOUNT, DIVIDEND_LAST_DATE, DIVIDEND_ACCRUED_DATE, DIVIDEND_ACCRUED_AMOUNT, DIVIDEND_APYE_START_DATE, DIVIDEND_APYE_DAILY_BAL, ACH_DEPOSIT_LAST_AMOUNT,
	ACH_DEPOSIT_LAST_DATE, REG_D_COUNT, REG_D_COUNT_PRIOR, REG_D_PAY, REG_D_PAY_CH_DATE, CRED_REP_PRIMARY_CONS_FIN_DATE	
	FROM CTE
	WHERE rn = 1;

	-- DUPE CHECK / DELETE 
	DELETE FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_SHARE_STG_CF USING (
    	WITH CTE_DUP AS
    	(
    	SELECT SERIAL,
	 	ROW_NUMBER () OVER ( PARTITION BY SERIAL ORDER BY SERIAL) AS RN
	 	FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_SHARE_STG_CF
    	)
        SELECT SERIAL, RN FROM CTE_DUP
        ) AS CTE_RESULT
	WHERE CTE_RESULT.RN > 1;

	-- ADD PRIMARY KEY BACK

	ALTER TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_SHARE_STG_CF ADD PRIMARY KEY (SERIAL);

	-- Expiration for records not coming back into resultset
	UPDATE RRCU_DW_DEV.DW.T_KS_SHARE_DW_CF
	SET SHAR_CURR_IND = 0
	, SHAR_EXP_DT = CURRENT_DATE
	WHERE SHAR_CURR_IND = 1
	AND SHAR_SERIAL NOT IN (SELECT SERIAL FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_SHARE_STG_CF);

	DROP TABLE IF EXISTS RRCU_STG_DEV.KEYSTONE_CORE.Update_STG;

	CREATE TEMPORARY TABLE RRCU_STG_DEV.KEYSTONE_CORE.Update_STG(
	SHAR_REC_KEY BIGINT,
	STG_SOURCEHASH2 VARCHAR(32),
	NEW_SOURCEHASH2 VARCHAR(32),
	IS_TYPE2 INT,  -- REPRESENTS TYPE 2
	IS_NEW INT -- INDICATION FOR NEW RECORD TYPE 2
	);


	INSERT INTO RRCU_STG_DEV.KEYSTONE_CORE.Update_STG (
	SHAR_REC_KEY,
	STG_SOURCEHASH2,
	NEW_SOURCEHASH2,
	IS_NEW,
	IS_TYPE2	
	)
	
	WITH CTE_COMPARE AS
	(
	SELECT dim.SHAR_REC_KEY ,  dim.SHAR_SOURCEHASH2, stg.sourcehash2,
	CASE WHEN dim.SHAR_REC_KEY IS NULL THEN 1 ELSE 0 END CASE,
	CASE WHEN dim.SHAR_REC_KEY IS NOT NULL AND stg.SOURCEHASH2 <> dim.SHAR_SOURCEHASH2 THEN 1 ELSE 0 END CASE
	FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_SHARE_STG_CF stg
	LEFT OUTER JOIN RRCU_DW_DEV.DW.T_KS_SHARE_DW_CF dim ON dim.SHAR_SERIAL = stg.SERIAL AND dim.SHAR_CURR_IND  = 1
	)
	SELECT *
	FROM CTE_COMPARE;

	UPDATE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_SHARE_STG_CF a
	SET SHAR_REC_KEY = b.SHAR_REC_KEY,
	ISNEW = b.IS_NEW,
	ISTYPE2 = b.IS_TYPE2
	FROM (SELECT SHAR_REC_KEY, IS_NEW, IS_TYPE2, NEW_SOURCEHASH2 FROM RRCU_STG_DEV.KEYSTONE_CORE.Update_STG) b
	WHERE a.SOURCEHASH2 = b.NEW_SOURCEHASH2 AND a.SHAR_REC_KEY IS NULL;

	-- Expiration for records type 2
	
   UPDATE RRCU_DW_DEV.DW.T_KS_SHARE_DW_CF
	SET SHAR_CURR_IND = 0
	, SHAR_EXP_DT = CURRENT_DATE
	WHERE SHAR_CURR_IND = 1
	AND SHAR_SERIAL IN (SELECT SERIAL FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_SHARE_STG_CF WHERE ISTYPE2 = 1); 

	INSERT INTO RRCU_DW_DEV.DW.T_KS_SHARE_DW_CF
	(
	SHAR_SERIAL,
	SHAR_CURR_IND, 
	SHAR_EFF_DT, 
	SHAR_EXP_DT, 
	--SHAR_MOD_DT, 
	SHAR_SOURCEHASH2, 
	SHAR_PARENT_SERIAL, 
	SHAR_STORED_ACCESS_KEY, 
	SHAR_ORDINAL, 
	SHAR_LAST_FM_DATE, 
	SHAR_ID, 
	SHAR_DESCRIPTION, 
	SHAR_TYPE_SERIAL, 
	SHAR_PROCESSING, 
	SHAR_BRANCH_SERIAL, 
	SHAR_OPEN_DATE, 
	SHAR_OPENED_BY_USER_SERIAL, 
	SHAR_CLOSE_DATE, 
	SHAR_CLOSE_REASON_SERIAL, 
	SHAR_CHARGE_OFF_TYPE_SERIAL, 
	SHAR_CHARGE_OFF_DATE, 
	SHAR_CHARGE_OFF_AMOUNT, 
	SHAR_COLLECTION_STATUS, 
	SHAR_COLLECTION_HANDLING, 
	SHAR_COLLECTION_NOTICE_COUNT, 
	SHAR_COLLECTION_NOTICE_DATE, 
	SHAR_CRED_REP_PRIMARY_ECOA_CODE, 
	SHAR_CRED_REP_PRIMARY_CONS_INFO_IND, 
	SHAR_CRED_REP_BANKRUPTCY_DATE, 
	SHAR_CRED_REP_ACCOUNT_TYPE, 
	SHAR_CRED_REP_SPEC_COMM_CODE, 
	SHAR_CRED_REP_COMP_COND_CODE, 
	SHAR_CRED_REP_FIRST_DQ_DATE, 
	SHAR_CRED_REP_ACCOUNT_STATUS, 
	SHAR_CRED_REP_LAST_DATE, 
	SHAR_SHARED_BRANCH_OPTION, 
	SHAR_NOTE_RESTRICTION,
	SHAR_DEPOSIT_RESTRICTION, 
	SHAR_WITHDRAWAL_RESTRICTION, 
	SHAR_MONETARY_PURGE_DATE, 
	SHAR_LAST_MONETARY_DATE, 
	SHAR_LAST_ACTIVITY_DATE, 
	SHAR_BALANCE, 
	SHAR_MINIMUM_BALANCE, 
	SHAR_MINIMUM_DEPOSIT, 
	SHAR_MINIMUM_WITHDRAWAL, 
	SHAR_SWEEP_OPTION, 
	SHAR_SWEEP_TARGET_BALANCE, 
	SHAR_SWEEP_MINIMUM_BALANCE, 
	SHAR_SWEEP_MAXIMUM_BALANCE,
	SHAR_COURTESY_PAY_LIMIT, 
	SHAR_COURTESY_PAY_RESTRICT_SERIAL, 
	SHAR_COURTESY_PAY_ATM_DEBIT, 
	SHAR_COURTESY_PAY_ATM_DEBIT_CH_DATE, 
	SHAR_COURTESY_PAY_OTHER, 
	SHAR_COURTESY_PAY_OTHER_CH_DATE, 
	SHAR_POSITIVE_PAY_OPTION, 
	SHAR_CK_HLD_NEXT_DAY_AVAIL_AMOUNT, 
	SHAR_OPENING_BALANCE, 
	SHAR_ORIGINAL_AMOUNT, 
	SHAR_ORIGINAL_DATE, 
	SHAR_CERT_NUMBER, 
	SHAR_CERT_PEN_CALCULATION_SERIAL, 
	SHAR_CERT_PEN_WAIVE_COUNT, 
	SHAR_CERT_PEN_WAIVE_LAST_DATE, 
	SHAR_CERT_DIVIDENDS_AVAILABLE, 
	SHAR_CERT_OID_YIELD_TO_MATURITY, 
	SHAR_CERT_OID_BALANCE, 
	SHAR_CERT_BUMP_COUNT, 
	SHAR_CERT_BUMP_LAST_DATE, 
	SHAR_MATURITY_POSTING, 
	SHAR_MATURITY_FREQUENCY, 
	SHAR_MATURITY_PERIOD, 
	SHAR_MATURITY_DATE, 
	SHAR_MATURITY_LAST_DATE, 
	SHAR_MATURITY_RENEW_DEFAULTS_SERIAL, 
	SHAR_MAIL_PERSON_ADDR_LINK_SERIAL, 
	SHAR_STMT_MAIL_GROUP_SERIAL, 
	SHAR_STMT_CUTOFF_GROUP_SERIAL, 
	SHAR_STMT_CUTOFF_LAST_DATE, 
	SHAR_STMT_CUTOFF_LAST_TRAN_SERIAL, 
	SHAR_STMT_CUTOFF_PRIOR_DATE, 
	SHAR_STMT_CUTOFF_PRIOR_TRAN_SERIAL, 
	SHAR_STMT_REG_E_COUNT, 
	SHAR_ANALYSIS_CATEGORY, 
	SHAR_ANALYSIS_SHARE_SERIAL, 
	SHAR_TAX_PERSON_SERIAL, 
	SHAR_TAX_PLAN_CATEGORY, 
	SHAR_TAX_PLAN_SERIAL, 
	SHAR_DIVIDEND_CALCULATION_SERIAL, 
	SHAR_DIVIDEND_POSTING, 
	SHAR_DIVIDEND_CUSTOM_RATE, 
	SHAR_DIVIDEND_LAST_AMOUNT, 
	SHAR_DIVIDEND_LAST_DATE, 
	SHAR_DIVIDEND_ACCRUED_DATE, 
	SHAR_DIVIDEND_ACCRUED_AMOUNT, 
	SHAR_DIVIDEND_APYE_START_DATE, 
	SHAR_DIVIDEND_APYE_DAILY_BAL, 
	SHAR_ACH_DEPOSIT_LAST_AMOUNT, 
	SHAR_ACH_DEPOSIT_LAST_DATE, 
	SHAR_REG_D_COUNT, 
	SHAR_REG_D_COUNT_PRIOR, 
	SHAR_REG_D_PAY, 
	SHAR_REG_D_PAY_CH_DATE, 
	DW_LOAD_DT
	)

	SELECT 
	stg.SERIAL,
	1,
	CURRENT_DATE,
	NULL,
	stg.SOURCEHASH2,
	stg.PARENT_SERIAL, 
	stg.STORED_ACCESS_KEY, 
	stg.ORDINAL, 
	stg.LAST_FM_DATE, 
	stg.ID, 
	stg.DESCRIPTION, 
	stg.TYPE_SERIAL, 
	stg.PROCESSING, 
	stg.BRANCH_SERIAL, 
	stg.OPEN_DATE, 
	stg.OPENED_BY_USER_SERIAL, 
	stg.CLOSE_DATE,
	stg.CLOSE_REASON_SERIAL, 
	stg.CHARGE_OFF_TYPE_SERIAL,
	stg.CHARGE_OFF_DATE, 
	stg.CHARGE_OFF_AMOUNT, 
	stg.COLLECTION_STATUS, 
	stg.COLLECTION_HANDLING, 
	stg.COLLECTION_NOTICE_COUNT, 
	stg.COLLECTION_NOTICE_DATE, 
	stg.CRED_REP_PRIMARY_ECOA_CODE, 
	stg.CRED_REP_PRIMARY_CONS_INFO_IND, 
	stg.CRED_REP_BANKRUPTCY_DATE, 
	stg.CRED_REP_ACCOUNT_TYPE, 
	stg.CRED_REP_SPEC_COMM_CODE, 
	stg.CRED_REP_COMP_COND_CODE, 
	stg.CRED_REP_FIRST_DQ_DATE,
	stg.CRED_REP_ACCOUNT_STATUS, 
	stg.CRED_REP_LAST_DATE, 
	--CRED_REP_PRIMARY_CONS_FIN_DATE,		
	stg.SHARED_BRANCH_OPTION, 
	stg.NOTE_RESTRICTION, 
	stg.DEPOSIT_RESTRICTION, 
	stg.WITHDRAWAL_RESTRICTION, 
	stg.MONETARY_PURGE_DATE, 
	stg.LAST_MONETARY_DATE, 
	stg.LAST_ACTIVITY_DATE, 
	stg.BALANCE, 
	stg.MINIMUM_BALANCE, 
	stg.MINIMUM_DEPOSIT, 
	stg.MINIMUM_WITHDRAWAL, 
	stg.SWEEP_OPTION, 
	stg.SWEEP_TARGET_BALANCE, 
	stg.SWEEP_MINIMUM_BALANCE, 
	stg.SWEEP_MAXIMUM_BALANCE, 
	stg.COURTESY_PAY_LIMIT, 
	stg.COURTESY_PAY_RESTRICT_SERIAL, 
	stg.COURTESY_PAY_ATM_DEBIT, 
	stg.COURTESY_PAY_ATM_DEBIT_CH_DATE, 
	stg.COURTESY_PAY_OTHER, 
	stg.COURTESY_PAY_OTHER_CH_DATE, 
	stg.POSITIVE_PAY_OPTION, 
	stg.CK_HLD_NEXT_DAY_AVAIL_AMOUNT, 
	stg.OPENING_BALANCE, 
	stg.ORIGINAL_AMOUNT, 
	stg.ORIGINAL_DATE, 
	stg.CERT_NUMBER, 
	stg.CERT_PEN_CALCULATION_SERIAL, 
	stg.CERT_PEN_WAIVE_COUNT, 
	stg.CERT_PEN_WAIVE_LAST_DATE, 
	stg.CERT_DIVIDENDS_AVAILABLE, 
	stg.CERT_OID_YIELD_TO_MATURITY, 
	stg.CERT_OID_BALANCE, 
	stg.CERT_BUMP_COUNT, 
	stg.CERT_BUMP_LAST_DATE, 
	stg.MATURITY_POSTING, 
	stg.MATURITY_FREQUENCY, 
	stg.MATURITY_PERIOD, 
	stg.MATURITY_DATE,
	stg.MATURITY_LAST_DATE, 
	stg.MATURITY_RENEW_DEFAULTS_SERIAL, 
	stg.MAIL_PERSON_ADDR_LINK_SERIAL, 
	stg.STMT_MAIL_GROUP_SERIAL, 
	stg.STMT_CUTOFF_GROUP_SERIAL, 
	stg.STMT_CUTOFF_LAST_DATE, 
	stg.STMT_CUTOFF_LAST_TRAN_SERIAL, 
	stg.STMT_CUTOFF_PRIOR_DATE, 
	stg.STMT_CUTOFF_PRIOR_TRAN_SERIAL, 
	stg.STMT_REG_E_COUNT, 
	stg.ANALYSIS_CATEGORY, 
	stg.ANALYSIS_SHARE_SERIAL, 
	stg.TAX_PERSON_SERIAL, 
	stg.TAX_PLAN_CATEGORY, 
	stg.TAX_PLAN_SERIAL, 
	stg.DIVIDEND_CALCULATION_SERIAL, 
	stg.DIVIDEND_POSTING, 
	stg.DIVIDEND_CUSTOM_RATE, 
	stg.DIVIDEND_LAST_AMOUNT, 
	stg.DIVIDEND_LAST_DATE, 
	stg.DIVIDEND_ACCRUED_DATE, 
	stg.DIVIDEND_ACCRUED_AMOUNT, 
	stg.DIVIDEND_APYE_START_DATE, 
	stg.DIVIDEND_APYE_DAILY_BAL, 
	stg.ACH_DEPOSIT_LAST_AMOUNT,
	stg.ACH_DEPOSIT_LAST_DATE, 
	stg.REG_D_COUNT,
	stg.REG_D_COUNT_PRIOR, 
	stg.REG_D_PAY, 
	stg.REG_D_PAY_CH_DATE, 	
	CURRENT_DATE
	FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_SHARE_STG_CF stg
		WHERE ISNEW = 1 OR ISTYPE2 = 1;

	-- Business rules around dates for current records
	UPDATE RRCU_DW_DEV.DW.T_KS_SHARE_DW_CF
	SET SHAR_CURR_IND = 0
	, SHAR_EXP_DT = CURRENT_DATE
	WHERE SHAR_CLOSE_DATE <= CURRENT_DATE
	AND SHAR_CURR_IND = 1;

	UPDATE RRCU_DW_DEV.DW.T_KS_SHARE_DW_CF
	SET SHAR_CURR_IND = 0
	, SHAR_EXP_DT = CURRENT_DATE
	WHERE SHAR_MATURITY_DATE <= CURRENT_DATE
	AND SHAR_CURR_IND = 1;

	UPDATE RRCU_DW_DEV.DW.T_KS_SHARE_DW_CF
	SET SHAR_CURR_IND = 0
	, SHAR_EXP_DT = CURRENT_DATE
	WHERE SHAR_CHARGE_OFF_DATE  <= CURRENT_DATE
	AND SHAR_CURR_IND = 1;

END;
$$
;
