--==================================================================================================
--Author: Farr, C
--Create Date:	2024-04-24  	
--Object Name:	sp_LOAD_T_PERSON_CONTACT_DIM
--Description:  Loading Person Contact Data
--***********************************************************************************************************************
--Date			Trello#					ChangedBy						Description 
------------------------------------------------------------------------------------------------------------------------


CREATE OR REPLACE PROCEDURE RRCU_DW_DEV.DM.sp_LOAD_T_PERSON_CONTACT_DIM()
RETURNS VARCHAR NOT NULL
LANGUAGE SQL

AS
$$

BEGIN 


TRUNCATE TABLE RRCU_DW_DEV.DM.T_PERSON_CONTACT_DIM_CF;


INSERT INTO RRCU_DW_DEV.DM.T_PERSON_CONTACT_DIM_CF
(
SERIAL,
BUS_FULL_ADDR_NM, 
RES_FULL_ADDR_NM, 
MAIL_FULL_ADDR_NM, 
BUS_ADDR1_NM, 
BUS_ADDR2_NM, 
BUS_CITY_NM, 
BUS_STATE_NM, 
BUS_POSTAL_CD, 
BUS_COUNTRY_NM, 
BUS_PHONE_NUM, 
RES_ADDR1_NM, 
RES_ADDR2_NM, 
RES_CITY_NM, 
RES_STATE_NM, 
RES_POSTAL_CD, 
RES_COUNTRY_NM, 
RES_PHONE_NUM, 
CELL_PHONE_NUM, 
MAIL_ADDR1_NM, 
MAIL_ADDR2_NM, 
MAIL_CITY_NM, 
MAIL_STATE_NM, 
MAIL_POSTAL_CD, 
MAIL_COUNTRY_NM, 
PERS_EMAIL_NM, 
BUS_EMAIL_NM, 
DL_ID_NUM, 
DL_ID_ISSUER_NM, 
DL_ID_EXP_DT, 
SI_ID_NUM, 
SI_ID_ISSUER_NM, 
SI_ID_EXP_DT, 
PN_ID_NUM, 
PN_ID_ISSUER_NM, 
PN_ID_EXP_DT, 
CU_ID_NUM, 
CU_ID_ISSUER_NM, 
CU_ID_EXP_DT
)


SELECT 
P.SERIAL AS SERIAL,
MAX(CASE
	WHEN PAL.PSNADDR_CATEGORY='B' THEN CONCAT(A.ADDR_STREET,  ', ',  A.ADDR_CITY,  ', ', A.ADDR_STATE,  ' ', A.ADDR_POSTAL_CODE)
	ELSE NULL END) AS BUS_FULL_ADDR_NM,
MAX(CASE
	WHEN PAL.PSNADDR_CATEGORY='R' THEN CONCAT(A.ADDR_STREET,  ', ',  A.ADDR_CITY,  ', ', A.ADDR_STATE,  ' ', A.ADDR_POSTAL_CODE)
	ELSE NULL END) AS RES_FULL_ADDR_NM,
MAX(CASE
	WHEN PAL.PSNADDR_CATEGORY='M' THEN CONCAT(A.ADDR_STREET,  ', ',  A.ADDR_CITY,  ', ', A.ADDR_STATE,  ' ', A.ADDR_POSTAL_CODE)
	ELSE NULL END) AS RES_FULL_ADDR_NM,
	CASE
	WHEN PAL.PSNADDR_CATEGORY='B' THEN A.ADDR_STREET
	ELSE NULL END AS BUS_ADDR1_NM,
CASE
	WHEN PAL.PSNADDR_CATEGORY='B' THEN A.ADDR_ADDITIONAL_ADDRESS_LINE
	ELSE NULL END AS BUS_ADDR2_NM,
CASE
	WHEN PAL.PSNADDR_CATEGORY='B' THEN A.ADDR_CITY
	ELSE NULL END AS BUS_CITY_NM,
CASE
	WHEN PAL.PSNADDR_CATEGORY='B' THEN A.ADDR_STATE
	ELSE NULL END AS BUS_STATE_NM,
CASE
	WHEN PAL.PSNADDR_CATEGORY='B' THEN A.ADDR_POSTAL_CODE
	ELSE NULL END AS BUS_POSTAL_CD,
CASE
	WHEN PAL.PSNADDR_CATEGORY='B' THEN A.ADDR_COUNTRY
	ELSE NULL END AS BUS_COUNTRY_NM,
NULL AS BUS_PHONE_NUM,
--MAX(CASE
--WHEN PC.PSNCONT_CATEGORY = 'BP' THEN PC.PSNCONT_VALUE
--ELSE NULL END) AS BUS_PHONE_NUM,	
CASE
	WHEN PAL.PSNADDR_CATEGORY='R' THEN A.ADDR_STREET
	ELSE NULL END AS RES_ADDR1_NM,
CASE
	WHEN PAL.PSNADDR_CATEGORY='R' THEN A.ADDR_ADDITIONAL_ADDRESS_LINE
	ELSE NULL END AS RES_ADDR2_NM,
CASE
	WHEN PAL.PSNADDR_CATEGORY='R' THEN A.ADDR_CITY
	ELSE NULL END AS RES_CITY_NM,
CASE
	WHEN PAL.PSNADDR_CATEGORY='R' THEN A.ADDR_STATE
	ELSE NULL END AS RES_STATE_NM,
CASE
	WHEN PAL.PSNADDR_CATEGORY='R' THEN A.ADDR_POSTAL_CODE
	ELSE NULL END AS RES_POSTAL_CD,
CASE
	WHEN PAL.PSNADDR_CATEGORY='R' THEN A.ADDR_COUNTRY
	ELSE NULL END AS RES_COUNTRY_NM,
NULL AS RES_PHONE_NUM,
NULL AS CELL_PHONE_NUM,
--CASE
--	WHEN PC.PSNCONT_CATEGORY = 'HP' THEN PC.PSNCONT_VALUE
--	ELSE NULL END AS RES_PHONE_NUM,

--	MAX(CASE
--	WHEN PC.PSNCONT_CATEGORY = 'PC' THEN PC.PSNCONT_VALUE
--	ELSE NULL END) AS CELL_PHONE_NUM,
CASE
	WHEN PAL.PSNADDR_CATEGORY='M' THEN A.ADDR_STREET
	ELSE NULL END AS MAIL_ADDR1_NM,
CASE
	WHEN PAL.PSNADDR_CATEGORY='M' THEN A.ADDR_ADDITIONAL_ADDRESS_LINE
	ELSE NULL END AS MAIL_ADDR2_NM,
CASE
	WHEN PAL.PSNADDR_CATEGORY='M' THEN A.ADDR_CITY
	ELSE NULL END AS MAIL_CITY_NM,
CASE
	WHEN PAL.PSNADDR_CATEGORY='M' THEN A.ADDR_STATE
	ELSE NULL END AS MAIL_STATE_NM,
CASE
	WHEN PAL.PSNADDR_CATEGORY='M' THEN A.ADDR_POSTAL_CODE
	ELSE NULL END AS MAIL_POSTAL_CD,
CASE
	WHEN PAL.PSNADDR_CATEGORY='M' THEN A.ADDR_COUNTRY
	ELSE NULL END AS MAIL_COUNTRY_NM,
NULL AS PERS_EMAIL_NM,	
NULL AS BUS_EMAIL_NM,
--MAX(CASE
--	WHEN PC.PSNCONT_CATEGORY = 'PE' THEN PC.PSNCONT_VALUE
--	ELSE NULL END) AS PERS_EMAIL_NM,
--CASE
--	WHEN PC.PSNCONT_CATEGORY = 'BE' THEN PC.PSNCONT_VALUE
--	ELSE NULL END AS BUS_EMAIL_NM,
CASE
	WHEN PID.PSNID_CATEGORY ='DL' THEN PID.PSNID_VALUE
	ELSE NULL END AS DL_ID_NUM,
CASE 
	WHEN PID.PSNID_CATEGORY='DL' THEN PID.PSNID_ISSUER 
	ELSE NULL END AS DL_ID_ISSUER_NM,
CASE 
	WHEN PID.PSNID_CATEGORY='DL' THEN PID.PSNID_EXPIRATION_DATE
	ELSE NULL END AS DL_ID_EXP_DT,
CASE 
	WHEN PID.PSNID_CATEGORY='SI' THEN PID.PSNID_VALUE 
	ELSE NULL END AS SI_ID_NUM,
CASE 
	WHEN PID.PSNID_CATEGORY='SI' THEN PID.PSNID_ISSUER 
	ELSE NULL END AS SI_ID_ISSUER_NM,
CASE
	WHEN PID.PSNID_CATEGORY='SI' THEN PID.PSNID_EXPIRATION_DATE
	ELSE NULL END AS SI_ID_EXP_DT,
CASE
	WHEN PID.PSNID_CATEGORY='PN' THEN PID.PSNID_VALUE 
	ELSE NULL END AS PN_ID_NUM,
CASE 
	WHEN PID.PSNID_CATEGORY='PN' THEN PID.PSNID_ISSUER 
	ELSE NULL END AS PN_ID_ISSUER_NM,
CASE 
	WHEN PID.PSNID_CATEGORY='PN' THEN PID.PSNID_EXPIRATION_DATE 
	ELSE NULL END AS PN_ID_EXP_DT,
CASE 
	WHEN PID.PSNID_CATEGORY='CU' THEN PID.PSNID_VALUE 
	ELSE NULL END AS CU_ID_NUM,
CASE 
	WHEN PID.PSNID_CATEGORY='CU' THEN PID.PSNID_ISSUER 
ELSE NULL END AS CU_ID_ISSUER_NM,
CASE 
	WHEN PID.PSNID_CATEGORY='CU' THEN PID.PSNID_EXPIRATION_DATE
	ELSE NULL END AS CU_ID_EXP_DT	


FROM RRCU_DW_DEV.DW.T_KS_PERSON_ADDRESS_LINK_DW_CF PAL
LEFT OUTER JOIN RRCU_DW_DEV.DW.T_KS_ADDRESS_DW_CF A ON PAL.PSNADDR_ADDRESS_SERIAL = A.ADDR_SERIAL AND A.ADDR_CURR_IND = 1
LEFT OUTER JOIN RRCU_DW_DEV.DM.T_PERSON_DIM_CF P ON PAL.PSNADDR_PARENT_SERIAL  = P.SERIAL 
--LEFT OUTER JOIN RRCU_DW_DEV.DW.T_KS_PERSON_CONTACT_DW_CF PC ON P.SERIAL = PC.PSNCONT_PARENT_SERIAL AND PC.PSNCONT_CURR_IND = 1
LEFT OUTER JOIN RRCU_DW_DEV.DW.T_KS_PERSON_ID_DW_CF PID ON P.SERIAL = PID.PSNID_PARENT_SERIAL AND PID.PSNID_CURR_IND = 1


WHERE PAL.PSNADDR_CURR_IND = 1
AND P.SERIAL IS NOT NULL
GROUP BY P.SERIAL, PAL.PSNADDR_CATEGORY, A.ADDR_STREET, A.ADDR_ADDITIONAL_ADDRESS_LINE, A.ADDR_CITY,  A.ADDR_STATE, A.ADDR_POSTAL_CODE,
 A.ADDR_COUNTRY, PID.PSNID_CATEGORY, PID.PSNID_VALUE, PID.PSNID_ISSUER, PID.PSNID_EXPIRATION_DATE;

END
$$
;
 


UPDATE RRCU_DW_DEV.DM.T_PERSON_CONTACT_DIM_CF
SET bus_phone_num = dw.PSNCONT_VALUE

SELECT *
FROM RRCU_DW_DEV.DM.T_PERSON_DIM_CF x
JOIN RRCU_DW_DEV.DW.T_KS_PERSON_CONTACT_DW_CF dw ON  x.SERIAL = dw.PSNCONT_PARENT_SERIAL
WHERE dw.PSNCONT_CURR_IND = 1 AND dw.PSNCONT_CATEGORY = 'BP';



SELECT *
FROM RRCU_DW_DEV.DM.T_PERSON_CONTACT_DIM_CF
WHERE bus_phone_num IS NOT null







