/*
--==================================================================================================
--Author: Farr, C
--Create Date:	2024-04-01  	
--Object Name:	sp_LOAD_T_LN_TYPE_STG
--Description:  Loading Loan Type Data
--***********************************************************************************************************************
--Date			Trello#					ChangedBy						Description 
------------------------------------------------------------------------------------------------------------------------
*/

CREATE OR REPLACE PROCEDURE RRCU_STG_DEV.KEYSTONE_CORE.sp_LOAD_T_LN_TYPE_STG()
RETURNS VARCHAR NOT NULL
LANGUAGE SQL

AS
$$

BEGIN 
	
	TRUNCATE TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_LN_TYPE_STG_CF;
	
	-- REMOVE PK	
	ALTER TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_LN_TYPE_STG_CF DROP PRIMARY KEY;
	
	-- Populate STAGING WITH CTE DATA
	INSERT INTO RRCU_STG_DEV.KEYSTONE_CORE.T_KS_LN_TYPE_STG_CF
	(
	SERIAL,
	SOURCEHASH2,
	LAST_FM_DATE, 
	DESCRIPTION, 
	STATUS, 
	CODE, 
	CATEGORY, 
	PROCESSING, 
	MINIMUM_BALANCE, 
	MINIMUM_ADVANCE, 
	CLOSE_OPTION, 
	DORMANCY_RESTRICTION_DAYS, 
	DQ_RESTRICTION_GRACE_DAYS, 
	DQ_RESTRICTION_GRACE_AMOUNT, 
	DQ_RESTRICTION_FORCE_DAYS, 
	PAYMENT_HANDLING,
	PAYMENT_APPLICATION, 
	PAYMENT_INTEREST_OPTION, 
	PAYMENT_LATE_FEE_OPTION, 
	PAYMENT_MAINTENANCE_FEE_OPTION, 
	PAYMENT_PARTIAL_OPTION, 
	PAYMENT_CALCULATION_SERIAL, 
	PAYMENT_AHEAD, 
	PAYMENT_AHEAD_COUNT, 
	REPAYMENT_CALCULATION_SERIAL, 
	REPAYMENT_AHEAD, 
	REPAYMENT_AHEAD_COUNT, 
	DRAW_PERIOD_EXPIRATION_MONTHS, 
	PAYMENT_SHORT_AMOUNT, 
	PAYMENT_SHORT_PERCENTAGE, 
	FIRST_DUE_DATE_CALCULATION, 
	FIRST_DUE_DATE_GRACE_DAYS, 
	INTEREST_CALCULATION, 
	CC_CALCULATION_SERIAL, 
	AVAILABLE_CALCULATION, 
	CRED_REP_PORTFOLIO_TYPE, 
	IRS_FORM_OPTION, 
	GUARANTEE_OPTION, 
	MLA_ELIGIBILITY, 
	EXT_INTERFACE_SERIAL, 
	COLLECTION_ITEM_TYPE_SERIAL, 
	COLLECTION_NOTICE_TYPE_SERIAL, 
	PAPER_GRADE_SCALE_SERIAL, 
	RISK_BASED_PRICING_SERIAL, 
	RISK_BASED_PRICING_PLAN_SERIAL, 
	DECISION_MODEL_SERIAL, 
	DEALER_COMPENSATION_SERIAL, 
	APP_FORM_PACKET_SERIAL,
	DEF_LOGIN_WITHDRAWAL_ACCESS, 
	DEF_LOGIN_DEPOSIT_ACCESS, 
	DEF_LOGIN_INQUIRY_ACCESS, 
	BALANCE_GL_SERIAL, 
	BALANCE_GL_BRANCH_ACCTING, 
	CHARGE_OFF_GL_SERIAL, 
	CHARGE_OFF_GL_BRANCH_ACCTING, 
	RECOVERY_GL_SERIAL, 
	RECOVERY_GL_BRANCH_ACCTING, 
	INTEREST_GL_SERIAL, 
	INTEREST_GL_BRANCH_ACCTING, 
	INT_ACCRUED_GL_SERIAL, 
	INT_ACCRUED_GL_BRANCH_ACCTING, 
	LATE_FEE_GL_SERIAL, 
	LATE_FEE_GL_BRANCH_ACCTING, 
	EXT_TRAN_GL_SERIAL, 
	EXT_TRAN_GL_BRANCH_ACCTING, 
	AIRES_CODE, 
	INTEREST_PD_AHD_PAYOFF_OPTION, 
	ORIGINAL_LN_DT_UPDATE_OPTION, 
	UNAPP_FUNDS_GL_SERIAL, 
	UNAPP_FUNDS_GL_BRANCH_ACCTING, 
	INSURANCE_PRODUCT_RESTRICTION, 
	RIGHT_TO_RESCIND_DAYS, 
	INTEREST_PST_DUE_PAYOFF_OPTION
	)
	
	WITH CTE AS

	(	
	SELECT 
	SERIAL,
	MD5(TO_VARCHAR(ARRAY_CONSTRUCT(*))) AS SourceHash2,  -- SOURCE HASH	
	LAST_FM_DATE, 
	DESCRIPTION, 
	STATUS, 
	CODE, 
	CATEGORY, 
	PROCESSING, 
	MINIMUM_BALANCE, 
	MINIMUM_ADVANCE, 
	CLOSE_OPTION, 
	DORMANCY_RESTRICTION_DAYS, 
	DQ_RESTRICTION_GRACE_DAYS, 
	DQ_RESTRICTION_GRACE_AMOUNT, 
	DQ_RESTRICTION_FORCE_DAYS, 
	PAYMENT_HANDLING,
	PAYMENT_APPLICATION, 
	PAYMENT_INTEREST_OPTION, 
	PAYMENT_LATE_FEE_OPTION, 
	PAYMENT_MAINTENANCE_FEE_OPTION, 
	PAYMENT_PARTIAL_OPTION, 
	PAYMENT_CALCULATION_SERIAL, 
	PAYMENT_AHEAD, 
	PAYMENT_AHEAD_COUNT, 
	REPAYMENT_CALCULATION_SERIAL, 
	REPAYMENT_AHEAD, 
	REPAYMENT_AHEAD_COUNT, 
	DRAW_PERIOD_EXPIRATION_MONTHS, 
	PAYMENT_SHORT_AMOUNT, 
	PAYMENT_SHORT_PERCENTAGE, 
	FIRST_DUE_DATE_CALCULATION, 
	FIRST_DUE_DATE_GRACE_DAYS, 
	INTEREST_CALCULATION, 
	CC_CALCULATION_SERIAL, 
	AVAILABLE_CALCULATION, 
	CRED_REP_PORTFOLIO_TYPE, 
	IRS_FORM_OPTION, 
	GUARANTEE_OPTION, 
	MLA_ELIGIBILITY, 
	EXT_INTERFACE_SERIAL, 
	COLLECTION_ITEM_TYPE_SERIAL, 
	COLLECTION_NOTICE_TYPE_SERIAL, 
	PAPER_GRADE_SCALE_SERIAL, 
	RISK_BASED_PRICING_SERIAL, 
	RISK_BASED_PRICING_PLAN_SERIAL, 
	DECISION_MODEL_SERIAL, 
	DEALER_COMPENSATION_SERIAL, 
	APP_FORM_PACKET_SERIAL,
	DEF_LOGIN_WITHDRAWAL_ACCESS, 
	DEF_LOGIN_DEPOSIT_ACCESS, 
	DEF_LOGIN_INQUIRY_ACCESS, 
	BALANCE_GL_SERIAL, 
	BALANCE_GL_BRANCH_ACCTING, 
	CHARGE_OFF_GL_SERIAL, 
	CHARGE_OFF_GL_BRANCH_ACCTING, 
	RECOVERY_GL_SERIAL, 
	RECOVERY_GL_BRANCH_ACCTING, 
	INTEREST_GL_SERIAL, 
	INTEREST_GL_BRANCH_ACCTING, 
	INT_ACCRUED_GL_SERIAL, 
	INT_ACCRUED_GL_BRANCH_ACCTING, 
	LATE_FEE_GL_SERIAL, 
	LATE_FEE_GL_BRANCH_ACCTING, 
	EXT_TRAN_GL_SERIAL, 
	EXT_TRAN_GL_BRANCH_ACCTING, 
	AIRES_CODE, 
	INTEREST_PD_AHD_PAYOFF_OPTION, 
	ORIGINAL_LN_DT_UPDATE_OPTION, 
	UNAPP_FUNDS_GL_SERIAL, 
	UNAPP_FUNDS_GL_BRANCH_ACCTING, 
	INSURANCE_PRODUCT_RESTRICTION, 
	RIGHT_TO_RESCIND_DAYS, 
	INTEREST_PST_DUE_PAYOFF_OPTION, 
	ROW_NUMBER() OVER (PARTITION BY SERIAL ORDER BY SERIAL) AS rn -- helps identify mutliple serial number dupes		
	FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_LN_TYPE_STG
	)

	SELECT SERIAL, SOURCEHASH2,	LAST_FM_DATE, DESCRIPTION, STATUS, CODE, CATEGORY, PROCESSING, MINIMUM_BALANCE, MINIMUM_ADVANCE, CLOSE_OPTION, DORMANCY_RESTRICTION_DAYS, 
	DQ_RESTRICTION_GRACE_DAYS, DQ_RESTRICTION_GRACE_AMOUNT, DQ_RESTRICTION_FORCE_DAYS, PAYMENT_HANDLING, PAYMENT_APPLICATION, PAYMENT_INTEREST_OPTION, PAYMENT_LATE_FEE_OPTION, 
	PAYMENT_MAINTENANCE_FEE_OPTION, PAYMENT_PARTIAL_OPTION, PAYMENT_CALCULATION_SERIAL, PAYMENT_AHEAD, PAYMENT_AHEAD_COUNT, REPAYMENT_CALCULATION_SERIAL, REPAYMENT_AHEAD, 
	REPAYMENT_AHEAD_COUNT, DRAW_PERIOD_EXPIRATION_MONTHS, PAYMENT_SHORT_AMOUNT, PAYMENT_SHORT_PERCENTAGE, FIRST_DUE_DATE_CALCULATION, FIRST_DUE_DATE_GRACE_DAYS, 
	INTEREST_CALCULATION, CC_CALCULATION_SERIAL, AVAILABLE_CALCULATION, CRED_REP_PORTFOLIO_TYPE, IRS_FORM_OPTION, GUARANTEE_OPTION, MLA_ELIGIBILITY, EXT_INTERFACE_SERIAL, 
	COLLECTION_ITEM_TYPE_SERIAL, COLLECTION_NOTICE_TYPE_SERIAL, PAPER_GRADE_SCALE_SERIAL, RISK_BASED_PRICING_SERIAL, RISK_BASED_PRICING_PLAN_SERIAL, DECISION_MODEL_SERIAL, 
	DEALER_COMPENSATION_SERIAL, APP_FORM_PACKET_SERIAL, DEF_LOGIN_WITHDRAWAL_ACCESS, DEF_LOGIN_DEPOSIT_ACCESS, DEF_LOGIN_INQUIRY_ACCESS, BALANCE_GL_SERIAL, 
	BALANCE_GL_BRANCH_ACCTING, CHARGE_OFF_GL_SERIAL, CHARGE_OFF_GL_BRANCH_ACCTING, RECOVERY_GL_SERIAL, RECOVERY_GL_BRANCH_ACCTING, INTEREST_GL_SERIAL, INTEREST_GL_BRANCH_ACCTING, 
	INT_ACCRUED_GL_SERIAL, INT_ACCRUED_GL_BRANCH_ACCTING, LATE_FEE_GL_SERIAL, LATE_FEE_GL_BRANCH_ACCTING, EXT_TRAN_GL_SERIAL, EXT_TRAN_GL_BRANCH_ACCTING, AIRES_CODE, 
	INTEREST_PD_AHD_PAYOFF_OPTION, ORIGINAL_LN_DT_UPDATE_OPTION, UNAPP_FUNDS_GL_SERIAL, UNAPP_FUNDS_GL_BRANCH_ACCTING, INSURANCE_PRODUCT_RESTRICTION, RIGHT_TO_RESCIND_DAYS, 
	INTEREST_PST_DUE_PAYOFF_OPTION
	FROM CTE
	WHERE rn = 1;
	
	-- DUPE CHECK / DELETE 
	DELETE FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_LN_TYPE_STG_CF USING (
    	WITH CTE_DUP AS
    	(
    	SELECT SERIAL,
	 	ROW_NUMBER () OVER ( PARTITION BY SERIAL ORDER BY SERIAL) AS RN
	 	FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_LN_TYPE_STG_CF
    	)
        SELECT SERIAL, RN FROM CTE_DUP
        ) AS CTE_RESULT
	WHERE CTE_RESULT.RN > 1;

	-- ADD PRIMARY KEY BACK

	ALTER TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_LN_TYPE_STG_CF ADD PRIMARY KEY (SERIAL);

	-- Expiration for records not coming back into resultset
	UPDATE RRCU_DW_DEV.DW.T_KS_LN_TYPE_DW_CF
	SET LNTYP_CURR_IND = 0
	, LNTYP_EXP_DT = CURRENT_DATE
	WHERE LNTYP_CURR_IND = 1
	AND LNTYP_SERIAL NOT IN (SELECT SERIAL FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_LN_TYPE_STG_CF);

	DROP TABLE IF EXISTS RRCU_STG_DEV.KEYSTONE_CORE.Update_STG;

	CREATE TEMPORARY TABLE RRCU_STG_DEV.KEYSTONE_CORE.Update_STG(
	LNTYP_REC_KEY BIGINT,
	STG_SOURCEHASH2 VARCHAR(32),
	NEW_SOURCEHASH2 VARCHAR(32),
	IS_TYPE2 INT,  -- REPRESENTS TYPE 2
	IS_NEW INT -- INDICATION FOR NEW RECORD TYPE 2
	);


	INSERT INTO RRCU_STG_DEV.KEYSTONE_CORE.Update_STG (
	LNTYP_REC_KEY,
	STG_SOURCEHASH2,
	NEW_SOURCEHASH2,
	IS_NEW,
	IS_TYPE2	
	)
	
	WITH CTE_COMPARE AS
	(
	SELECT dim.LNTYP_REC_KEY ,  dim.LNTYP_SOURCEHASH2, stg.sourcehash2,
	CASE WHEN dim.LNTYP_REC_KEY IS NULL THEN 1 ELSE 0 END CASE,
	CASE WHEN dim.LNTYP_REC_KEY IS NOT NULL AND stg.SOURCEHASH2 <> dim.LNTYP_SOURCEHASH2 THEN 1 ELSE 0 END CASE
	FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_LN_TYPE_STG_CF stg
	LEFT OUTER JOIN RRCU_DW_DEV.DW.T_KS_LN_TYPE_DW_CF dim ON dim.LNTYP_SERIAL = stg.SERIAL AND dim.LNTYP_CURR_IND  = 1
	)
	SELECT *
	FROM CTE_COMPARE;

	UPDATE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_LN_TYPE_STG_CF a
	SET LNTYP_REC_KEY = b.LNTYP_REC_KEY,
	ISNEW = b.IS_NEW,
	ISTYPE2 = b.IS_TYPE2
	FROM (SELECT LNTYP_REC_KEY, IS_NEW, IS_TYPE2, NEW_SOURCEHASH2 FROM RRCU_STG_DEV.KEYSTONE_CORE.Update_STG) b
	WHERE a.SOURCEHASH2 = b.NEW_SOURCEHASH2 AND a.LNTYP_REC_KEY IS NULL;

	-- Expiration for records type 2
	
   UPDATE RRCU_DW_DEV.DW.T_KS_LN_TYPE_DW_CF
	SET LNTYP_CURR_IND = 0
	, LNTYP_EXP_DT = CURRENT_DATE
	WHERE LNTYP_CURR_IND = 1
	AND LNTYP_SERIAL IN (SELECT SERIAL FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_LN_TYPE_STG_CF WHERE ISTYPE2 = 1); 

	INSERT INTO RRCU_DW_DEV.DW.T_KS_LN_TYPE_DW_CF
	(
	LNTYP_SERIAL,
	LNTYP_CURR_IND, 
	LNTYP_EFF_DT, 
	LNTYP_EXP_DT, 
	--LNTYP_MOD_DT, 
	LNTYP_SOURCEHASH2,  
	LNTYP_LAST_FM_DATE, 
	LNTYP_DESCRIPTION, 
	LNTYP_STATUS, 
	LNTYP_CODE, 
	LNTYP_CATEGORY, 
	LNTYP_PROCESSING, 
	LNTYP_MINIMUM_BALANCE, 
	LNTYP_MINIMUM_ADVANCE, 
	LNTYP_CLOSE_OPTION, 
	LNTYP_DORMANCY_RESTRICTION_DAYS, 
	LNTYP_DQ_RESTRICTION_GRACE_DAYS, 
	LNTYP_DQ_RESTRICTION_GRACE_AMOUNT, 
	LNTYP_DQ_RESTRICTION_FORCE_DAYS,
	LNTYP_PAYMENT_HANDLING, 
	LNTYP_PAYMENT_APPLICATION, 
	LNTYP_PAYMENT_INTEREST_OPTION, 
	LNTYP_PAYMENT_LATE_FEE_OPTION, 
	LNTYP_PAYMENT_MAINTENANCE_FEE_OPTION, 
	LNTYP_PAYMENT_PARTIAL_OPTION, 
	LNTYP_PAYMENT_CALCULATION_SERIAL, 
	LNTYP_PAYMENT_AHEAD, 
	LNTYP_PAYMENT_AHEAD_COUNT, 
	LNTYP_REPAYMENT_CALCULATION_SERIAL, 
	LNTYP_REPAYMENT_AHEAD, 
	LNTYP_REPAYMENT_AHEAD_COUNT, 
	LNTYP_DRAW_PERIOD_EXPIRATION_MONTHS, 
	LNTYP_PAYMENT_SHORT_AMOUNT, 
	LNTYP_PAYMENT_SHORT_PERCENTAGE, 
	LNTYP_FIRST_DUE_DATE_CALCULATION, 
	LNTYP_FIRST_DUE_DATE_GRACE_DAYS, 
	LNTYP_INTEREST_CALCULATION, 
	LNTYP_CC_CALCULATION_SERIAL, 
	LNTYP_AVAILABLE_CALCULATION, 
	LNTYP_CRED_REP_PORTFOLIO_TYPE, 
	LNTYP_IRS_FORM_OPTION, 
	LNTYP_GUARANTEE_OPTION, 
	LNTYP_MLA_ELIGIBILITY, 
	LNTYP_EXT_INTERFACE_SERIAL, 
	LNTYP_COLLECTION_ITEM_TYPE_SERIAL, 
	LNTYP_COLLECTION_NOTICE_TYPE_SERIAL, 
	LNTYP_PAPER_GRADE_SCALE_SERIAL, 
	LNTYP_RISK_BASED_PRICING_SERIAL, 
	LNTYP_RISK_BASED_PRICING_PLAN_SERIAL, 
	LNTYP_DECISION_MODEL_SERIAL, 
	LNTYP_DEALER_COMPENSATION_SERIAL, 
	LNTYP_APP_FORM_PACKET_SERIAL, 
	LNTYP_DEF_LOGIN_WITHDRAWAL_ACCESS, 
	LNTYP_DEF_LOGIN_DEPOSIT_ACCESS, 
	LNTYP_DEF_LOGIN_INQUIRY_ACCESS, 
	LNTYP_BALANCE_GL_SERIAL, 
	LNTYP_BALANCE_GL_BRANCH_ACCTING, 
	LNTYP_CHARGE_OFF_GL_SERIAL, 
	LNTYP_CHARGE_OFF_GL_BRANCH_ACCTING, 
	LNTYP_RECOVERY_GL_SERIAL, 
	LNTYP_RECOVERY_GL_BRANCH_ACCTING, 
	LNTYP_INTEREST_GL_SERIAL, 
	LNTYP_INTEREST_GL_BRANCH_ACCTING, 
	LNTYP_INT_ACCRUED_GL_SERIAL, 
	LNTYP_INT_ACCRUED_GL_BRANCH_ACCTING, 
	LNTYP_LATE_FEE_GL_SERIAL, 
	LNTYP_LATE_FEE_GL_BRANCH_ACCTING, 
	LNTYP_EXT_TRAN_GL_SERIAL, 
	LNTYP_EXT_TRAN_GL_BRANCH_ACCTING, 
	LNTYP_AIRES_CODE, 
	LNTYP_INTEREST_PD_AHD_PAYOFF_OPTION, 
	LNTYP_ORIGINAL_LN_DT_UPDATE_OPTION, 
	LNTYP_UNAPP_FUNDS_GL_SERIAL, 
	LNTYP_UNAPP_FUNDS_GL_BRANCH_ACCTING, 
	LNTYP_INSURANCE_PRODUCT_RESTRICTION, 
	LNTYP_RIGHT_TO_RESCIND_DAYS, 
	LNTYP_INTEREST_PST_DUE_PAYOFF_OPTION, 
	DW_LOAD_DT
	)
	
	SELECT 
	stg.SERIAL,
	1,
	CURRENT_DATE,
	NULL,
	stg.SOURCEHASH2,
	stg.LAST_FM_DATE, 
	stg.DESCRIPTION, 
	stg.STATUS, 
	stg.CODE, 
	stg.CATEGORY, 
	stg.PROCESSING, 
	stg.MINIMUM_BALANCE, 
	stg.MINIMUM_ADVANCE, 
	stg.CLOSE_OPTION, 
	stg.DORMANCY_RESTRICTION_DAYS, 
	stg.DQ_RESTRICTION_GRACE_DAYS, 
	stg.DQ_RESTRICTION_GRACE_AMOUNT, 
	stg.DQ_RESTRICTION_FORCE_DAYS, 
	stg.PAYMENT_HANDLING,
	stg.PAYMENT_APPLICATION, 
	stg.PAYMENT_INTEREST_OPTION, 
	stg.PAYMENT_LATE_FEE_OPTION, 
	stg.PAYMENT_MAINTENANCE_FEE_OPTION, 
	stg.PAYMENT_PARTIAL_OPTION, 
	stg.PAYMENT_CALCULATION_SERIAL, 
	stg.PAYMENT_AHEAD, 
	stg.PAYMENT_AHEAD_COUNT, 
	stg.REPAYMENT_CALCULATION_SERIAL, 
	stg.REPAYMENT_AHEAD, 
	stg.REPAYMENT_AHEAD_COUNT, 
	stg.DRAW_PERIOD_EXPIRATION_MONTHS, 
	stg.PAYMENT_SHORT_AMOUNT, 
	stg.PAYMENT_SHORT_PERCENTAGE, 
	stg.FIRST_DUE_DATE_CALCULATION, 
	stg.FIRST_DUE_DATE_GRACE_DAYS, 
	stg.INTEREST_CALCULATION, 
	stg.CC_CALCULATION_SERIAL, 
	stg.AVAILABLE_CALCULATION, 
	stg.CRED_REP_PORTFOLIO_TYPE, 
	stg.IRS_FORM_OPTION, 
	stg.GUARANTEE_OPTION, 
	stg.MLA_ELIGIBILITY, 
	stg.EXT_INTERFACE_SERIAL, 
	stg.COLLECTION_ITEM_TYPE_SERIAL, 
	stg.COLLECTION_NOTICE_TYPE_SERIAL, 
	stg.PAPER_GRADE_SCALE_SERIAL, 
	stg.RISK_BASED_PRICING_SERIAL, 
	stg.RISK_BASED_PRICING_PLAN_SERIAL, 
	stg.DECISION_MODEL_SERIAL, 
	stg.DEALER_COMPENSATION_SERIAL, 
	stg.APP_FORM_PACKET_SERIAL,
	stg.DEF_LOGIN_WITHDRAWAL_ACCESS, 
	stg.DEF_LOGIN_DEPOSIT_ACCESS, 
	stg.DEF_LOGIN_INQUIRY_ACCESS, 
	stg.BALANCE_GL_SERIAL, 
	stg.BALANCE_GL_BRANCH_ACCTING, 
	stg.CHARGE_OFF_GL_SERIAL, 
	stg.CHARGE_OFF_GL_BRANCH_ACCTING, 
	stg.RECOVERY_GL_SERIAL, 
	stg.RECOVERY_GL_BRANCH_ACCTING, 
	stg.INTEREST_GL_SERIAL, 
	stg.INTEREST_GL_BRANCH_ACCTING, 
	stg.INT_ACCRUED_GL_SERIAL, 
	stg.INT_ACCRUED_GL_BRANCH_ACCTING, 
	stg.LATE_FEE_GL_SERIAL, 
	stg.LATE_FEE_GL_BRANCH_ACCTING, 
	stg.EXT_TRAN_GL_SERIAL, 
	stg.EXT_TRAN_GL_BRANCH_ACCTING, 
	stg.AIRES_CODE, 
	stg.INTEREST_PD_AHD_PAYOFF_OPTION, 
	stg.ORIGINAL_LN_DT_UPDATE_OPTION, 
	stg.UNAPP_FUNDS_GL_SERIAL, 
	stg.UNAPP_FUNDS_GL_BRANCH_ACCTING, 
	stg.INSURANCE_PRODUCT_RESTRICTION, 
	stg.RIGHT_TO_RESCIND_DAYS, 
	stg.INTEREST_PST_DUE_PAYOFF_OPTION, 
	CURRENT_DATE
	FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_LN_TYPE_STG_CF stg
		WHERE ISNEW = 1 OR ISTYPE2 = 1;
	
	-- Business rules status for current records
	UPDATE RRCU_DW_DEV.DW.T_KS_LN_TYPE_DW_CF
	SET LNTYP_CURR_IND = 0,
	LNTYP_EXP_DT = CURRENT_DATE
	WHERE LNTYP_STATUS = 'C'
	AND LNTYP_EXP_DT IS NULL;


END;
$$
;






