--==================================================================================================
--Author: Farr, C
--Create Date:	2024-03-20  	
--Object Name:	sp_LOAD_T_KS_PERSON_ADDRESS_LINK_STG
--Description:  Loading Person Address Data
--***********************************************************************************************************************
--Date			Trello#					ChangedBy						Description 
------------------------------------------------------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE RRCU_STG_DEV.KEYSTONE_CORE.sp_LOAD_T_KS_PERSON_ADDRESS_LINK_STG ()
RETURNS VARCHAR NOT NULL
LANGUAGE SQL

AS
$$

BEGIN 
	
	TRUNCATE TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_PERSON_ADDRESS_LINK_STG_CF;
	
	-- REMOVE PK	
	ALTER TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_PERSON_ADDRESS_LINK_STG_CF DROP PRIMARY KEY;	


	-- Populate STAGING WITH CTE DATA
	INSERT INTO RRCU_STG_DEV.KEYSTONE_CORE.T_KS_PERSON_ADDRESS_LINK_STG_CF
	(
	SERIAL,
	SOURCEHASH2,
	PARENT_SERIAL, 
	ORDINAL, 
	LAST_FM_DATE, 
	ADDRESS_SERIAL, 
	CATEGORY, 
	BAD_ADDRESS, 
	TYPE_SERIAL, 
	EFFECTIVE_DATE, 
	EXPIRATION_DATE, 
	SEASON_START_MONTH, 
	SEASON_START_DAY, 
	SEASON_END_MONTH, 
	SEASON_END_DAY, 
	CRED_REP_ADDRESS_INDICATOR, 
	CRED_REP_RESIDENCE_CODE, 
	LAST_VERIFICATION_DATE, 
	OWN_RENT
	)
	
	WITH CTE AS

	(	
	SELECT 
	SERIAL,
	MD5(TO_VARCHAR(ARRAY_CONSTRUCT(*))) AS SourceHash2,  -- SOURCE HASH		
	PARENT_SERIAL,
	ORDINAL, 
	LAST_FM_DATE, 
	ADDRESS_SERIAL, 
	CATEGORY, 
	BAD_ADDRESS, 
	TYPE_SERIAL, 
	EFFECTIVE_DATE, 
	EXPIRATION_DATE, 
	SEASON_START_MONTH, 
	SEASON_START_DAY, 
	SEASON_END_MONTH, 
	SEASON_END_DAY, 
	CRED_REP_ADDRESS_INDICATOR, 
	CRED_REP_RESIDENCE_CODE, 
	LAST_VERIFICATION_DATE, 
	OWN_RENT,
	ROW_NUMBER() OVER (PARTITION BY SERIAL ORDER BY SERIAL) AS rn -- helps identify mutliple serial number dupes		
	FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_PERSON_ADDRESS_LINK_STG
	)
	

    SELECT SERIAL, sourcehash2, PARENT_SERIAL, ORDINAL, LAST_FM_DATE, ADDRESS_SERIAL, CATEGORY, BAD_ADDRESS, TYPE_SERIAL,
    EFFECTIVE_DATE, EXPIRATION_DATE, SEASON_START_MONTH, SEASON_START_DAY, SEASON_END_MONTH, SEASON_END_DAY, 
    CRED_REP_ADDRESS_INDICATOR, CRED_REP_RESIDENCE_CODE, LAST_VERIFICATION_DATE, OWN_RENT
	FROM CTE
	WHERE rn = 1;

	-- DUPE CHECK / DELETE 
	DELETE FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_PERSON_ADDRESS_LINK_STG_CF USING (
    	WITH CTE_DUP AS
    	(
    	SELECT SERIAL,
	 	ROW_NUMBER () OVER ( PARTITION BY SERIAL ORDER BY SERIAL) AS RN
	 	FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_PERSON_ADDRESS_LINK_STG_CF
    	)
        SELECT SERIAL, RN FROM CTE_DUP
        ) AS CTE_RESULT
	WHERE CTE_RESULT.RN > 1;

	-- ADD PRIMARY KEY BACK

	ALTER TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_PERSON_ADDRESS_LINK_STG_CF ADD PRIMARY KEY (SERIAL);

	-- Expiration for records not coming back into resultset
	UPDATE RRCU_DW_DEV.DW.T_KS_PERSON_ADDRESS_LINK_DW_CF
	SET PSNADDR_CURR_IND = 0
	, PSNADDR_EXP_DT = CURRENT_DATE
	WHERE PSNADDR_CURR_IND = 1
	AND PSNADDR_SERIAL NOT IN (SELECT SERIAL FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_PERSON_ADDRESS_LINK_STG_CF);

	DROP TABLE IF EXISTS RRCU_STG_DEV.KEYSTONE_CORE.Update_STG;

	CREATE TEMPORARY TABLE RRCU_STG_DEV.KEYSTONE_CORE.Update_STG(
	PSNADDR_REC_KEY BIGINT,
	STG_SOURCEHASH2 VARCHAR(32),
	NEW_SOURCEHASH2 VARCHAR(32),
	IS_TYPE2 INT,  -- REPRESENTS TYPE 2
	IS_NEW INT -- INDICATION FOR NEW RECORD TYPE 2
	);

	--DROP TABLE RRCU_STG_DEV.KEYSTONE_CORE.Update_STG;
	
	INSERT INTO RRCU_STG_DEV.KEYSTONE_CORE.Update_STG (
	PSNADDR_REC_KEY,
	STG_SOURCEHASH2,
	NEW_SOURCEHASH2,
	IS_NEW,
	IS_TYPE2	
	)
	
	WITH CTE_COMPARE AS
	(
	SELECT dim.PSNADDR_REC_KEY ,  dim.PSNADDR_SOURCEHASH2, stg.sourcehash2,
	CASE WHEN dim.PSNADDR_REC_KEY IS NULL THEN 1 ELSE 0 END CASE,
	CASE WHEN dim.PSNADDR_REC_KEY IS NOT NULL AND stg.SOURCEHASH2 <> dim.PSNADDR_SOURCEHASH2 THEN 1 ELSE 0 END CASE
	FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_PERSON_ADDRESS_LINK_STG_CF stg
	LEFT OUTER JOIN RRCU_DW_DEV.DW.T_KS_PERSON_ADDRESS_LINK_DW_CF dim ON dim.PSNADDR_SERIAL = stg.SERIAL AND dim.PSNADDR_CURR_IND  = 1
	)
	SELECT *
	FROM CTE_COMPARE;

	--SELECT * FROM RRCU_STG_DEV.KEYSTONE_CORE.Update_STG;
	--SELECT * FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_PERSON_ADDRESS_LINK_STG_CF;

	UPDATE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_PERSON_ADDRESS_LINK_STG_CF a
	SET PSNADDR_REC_KEY = b.PSNADDR_REC_KEY,
	ISNEW = b.IS_NEW,
	ISTYPE2 = b.IS_TYPE2
	FROM (SELECT PSNADDR_REC_KEY, IS_NEW, IS_TYPE2, NEW_SOURCEHASH2 FROM RRCU_STG_DEV.KEYSTONE_CORE.Update_STG) b
	WHERE a.SOURCEHASH2 = b.NEW_SOURCEHASH2 AND a.PSNADDR_REC_KEY IS NULL;

	--SELECT isnew, count(*)
	--FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_ACCOUNT_CLOSE_REASON_STG_CF
	--WHERE isnew = 1
	--GROUP BY isnew;

   -- Expiration for records type 2
	
    UPDATE RRCU_DW_DEV.DW.T_KS_PERSON_ADDRESS_LINK_DW_CF
	SET PSNADDR_CURR_IND = 0
	, PSNADDR_EXP_DT = CURRENT_DATE
	WHERE PSNADDR_CURR_IND = 1
	AND PSNADDR_SERIAL IN (SELECT SERIAL FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_PERSON_ADDRESS_LINK_STG_CF WHERE ISTYPE2 = 1); 

	INSERT INTO RRCU_DW_DEV.DW.T_KS_PERSON_ADDRESS_LINK_DW_CF
	(
	PSNADDR_SERIAL,
	PSNADDR_CURR_IND,
	PSNADDR_EFF_DT, 
	PSNADDR_EXP_DT, 
	--PSNADDR_MOD_DT, 
	PSNADDR_SOURCEHASH2, 
	PSNADDR_PARENT_SERIAL, 
	PSNADDR_ORDINAL, 
	PSNADDR_LAST_FM_DATE, 
	PSNADDR_ADDRESS_SERIAL, 
	PSNADDR_CATEGORY, 
	PSNADDR_BAD_ADDRESS, 
	PSNADDR_TYPE_SERIAL, 
	PSNADDR_EFFECTIVE_DATE, 
	PSNADDR_EXPIRATION_DATE, 
	PSNADDR_SEASON_START_MONTH, 
	PSNADDR_SEASON_START_DAY, 
	PSNADDR_SEASON_END_MONTH, 
	PSNADDR_SEASON_END_DAY, 
	PSNADDR_CRED_REP_ADDRESS_INDICATOR, 
	PSNADDR_CRED_REP_RESIDENCE_CODE, 
	PSNADDR_LAST_VERIFICATION_DATE, 
	PSNADDR_OWN_RENT, 
	DW_LOAD_DT
	)
	
	SELECT 
	stg.SERIAL,
	1,
	CURRENT_DATE,
	NULL,
	stg.SOURCEHASH2,
    stg.PARENT_SERIAL,
    stg.ORDINAL, 
    stg.LAST_FM_DATE, 
    stg.ADDRESS_SERIAL, 
    stg.CATEGORY, 
    stg.BAD_ADDRESS, 
    stg.TYPE_SERIAL, 
    stg.EFFECTIVE_DATE,
    stg.EXPIRATION_DATE, 
    stg.SEASON_START_MONTH, 
    stg.SEASON_START_DAY, 
    stg.SEASON_END_MONTH,
    stg.SEASON_END_DAY, 
    stg.CRED_REP_ADDRESS_INDICATOR,
    stg.CRED_REP_RESIDENCE_CODE, 
    stg.LAST_VERIFICATION_DATE, 
    stg.OWN_RENT,
    CURRENT_DATE

	FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_PERSON_ADDRESS_LINK_STG_CF stg
		WHERE ISNEW = 1 OR ISTYPE2 = 1;
	
	-- Epiriation of Expired Records less than Current Date still thinking they are curretn
	UPDATE RRCU_DW_DEV.DW.T_KS_PERSON_ADDRESS_LINK_DW_CF
	SET PSNADDR_CURR_IND = 0
	, PSNADDR_EXP_DT = CURRENT_DATE
	WHERE PSNADDR_EXPIRATION_DATE <= CURRENT_DATE;
	
END;
$$
;

