--==================================================================================================
--Author: Farr, C
--Create Date:	2024-03-27  	
--Object Name:	sp_LOAD_T_KS_PERSON_ID_STG
--Description:  Loading PERSON ID Data
--***********************************************************************************************************************
--Date			Trello#					ChangedBy						Description 
------------------------------------------------------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE RRCU_STG_DEV.KEYSTONE_CORE.sp_LOAD_T_KS_PERSON_ID_STG ()
RETURNS VARCHAR NOT NULL
LANGUAGE SQL

AS
$$

BEGIN 
	
	TRUNCATE TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_PERSON_ID_STG_CF;
	
	-- REMOVE PK	
	ALTER TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_PERSON_ID_STG_CF DROP PRIMARY KEY;	
	
	-- Populate STAGING WITH CTE DATA
	INSERT INTO RRCU_STG_DEV.KEYSTONE_CORE.T_KS_PERSON_ID_STG_CF
	(
	SERIAL,
	SOURCEHASH2,	
	PARENT_SERIAL, 
	ORDINAL, 
	CATEGORY, 
	DESCRIPTION, 
	VALUE, 
	EXPIRATION_DATE, 
	ISSUER, 
	ISSUE_DATE, 
	LAST_VERIFICATION_DATE,
	LAST_FM_DATE
	)
	
	WITH CTE AS

	(	
	SELECT 
	SERIAL,
	MD5(TO_VARCHAR(ARRAY_CONSTRUCT(*))) AS SourceHash2,  -- SOURCE HASH	
	PARENT_SERIAL, 
	ORDINAL, 
	CATEGORY, 
	DESCRIPTION, 
	VALUE, 
	EXPIRATION_DATE, 
	ISSUER, 
	ISSUE_DATE, 
	LAST_VERIFICATION_DATE, 
	LAST_FM_DATE,
	ROW_NUMBER() OVER (PARTITION BY SERIAL ORDER BY SERIAL) AS rn -- helps identify mutliple serial number dupes		
	FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_PERSON_ID_STG
	)

    SELECT SERIAL, SOURCEHASH2, PARENT_SERIAL, ORDINAL, CATEGORY, DESCRIPTION, VALUE, EXPIRATION_DATE, ISSUER, ISSUE_DATE, LAST_VERIFICATION_DATE, 
	LAST_FM_DATE,
	FROM CTE
	WHERE rn = 1;


	-- DUPE CHECK / DELETE 
	DELETE FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_PERSON_ID_STG_CF USING (
    	WITH CTE_DUP AS
    	(
    	SELECT SERIAL,
	 	ROW_NUMBER () OVER ( PARTITION BY SERIAL ORDER BY SERIAL) AS RN
	 	FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_PERSON_ID_STG_CF
    	)
        SELECT SERIAL, RN FROM CTE_DUP
        ) AS CTE_RESULT
	WHERE CTE_RESULT.RN > 1;

	-- ADD PRIMARY KEY BACK
	ALTER TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_PERSON_ID_STG_CF ADD PRIMARY KEY (SERIAL);

	-- Expiration for records not coming back into resultset
	UPDATE RRCU_DW_DEV.DW.T_KS_PERSON_ID_DW_CF
	SET PSNID_CURR_IND = 0
	, PSNID_EXP_DT = CURRENT_DATE
	WHERE PSNID_CURR_IND = 1
	AND PSNID_SERIAL NOT IN (SELECT SERIAL FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_PERSON_ID_STG_CF);

	DROP TABLE IF EXISTS RRCU_STG_DEV.KEYSTONE_CORE.Update_STG;

	CREATE TEMPORARY TABLE RRCU_STG_DEV.KEYSTONE_CORE.Update_STG(
	PSNID_REC_KEY BIGINT,
	STG_SOURCEHASH2 VARCHAR(32),
	NEW_SOURCEHASH2 VARCHAR(32),
	IS_TYPE2 INT,  -- REPRESENTS TYPE 2
	IS_NEW INT -- INDICATION FOR NEW RECORD TYPE 2
	);

	--DROP TABLE RRCU_STG_DEV.KEYSTONE_CORE.Update_STG;
	
	INSERT INTO RRCU_STG_DEV.KEYSTONE_CORE.Update_STG (
	PSNID_REC_KEY,
	STG_SOURCEHASH2,
	NEW_SOURCEHASH2,
	IS_NEW,
	IS_TYPE2	
	)
	
	WITH CTE_COMPARE AS
	(
	SELECT dim.PSNID_REC_KEY ,  dim.PSNID_SOURCEHASH2, stg.sourcehash2,
	CASE WHEN dim.PSNID_REC_KEY IS NULL THEN 1 ELSE 0 END CASE,
	CASE WHEN dim.PSNID_REC_KEY IS NOT NULL AND stg.SOURCEHASH2 <> dim.PSNID_SOURCEHASH2 THEN 1 ELSE 0 END CASE
	FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_PERSON_ID_STG_CF stg
	LEFT OUTER JOIN RRCU_DW_DEV.DW.T_KS_PERSON_ID_DW_CF dim ON dim.PSNID_SERIAL = stg.SERIAL AND dim.PSNID_CURR_IND  = 1
	)
	SELECT *
	FROM CTE_COMPARE;

	--SELECT * FROM RRCU_STG_DEV.KEYSTONE_CORE.Update_STG;
	--SELECT * FROM RRCU_STG_DEV.KEYSTONE_CORE..T_KS_ADDRESS_STG_CF;

	UPDATE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_PERSON_ID_STG_CF a
	SET PSNID_REC_KEY = b.PSNID_REC_KEY,
	ISNEW = b.IS_NEW,
	ISTYPE2 = b.IS_TYPE2
	FROM (SELECT PSNID_REC_KEY, IS_NEW, IS_TYPE2, NEW_SOURCEHASH2 FROM RRCU_STG_DEV.KEYSTONE_CORE.Update_STG) b
	WHERE a.SOURCEHASH2 = b.NEW_SOURCEHASH2 AND a.PSNID_REC_KEY IS NULL;

   -- Expiration for records type 2
	
    UPDATE RRCU_DW_DEV.DW.T_KS_PERSON_ID_DW_CF
	SET PSNID_CURR_IND = 0
	, PSNID_EXP_DT = CURRENT_DATE
	WHERE PSNID_CURR_IND = 1
	AND PSNID_SERIAL IN (SELECT SERIAL FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_PERSON_ID_STG_CF WHERE ISTYPE2 = 1); 

	INSERT INTO RRCU_DW_DEV.DW.T_KS_PERSON_ID_DW_CF
	(
	PSNID_SERIAL,
	PSNID_CURR_IND, 
	PSNID_EFF_DT, 
	PSNID_EXP_DT, 
	--PSNID_MOD_DT, 
	PSNID_SOURCEHASH2, 
	PSNID_PARENT_SERIAL, 
	PSNID_ORDINAL, 
	PSNID_CATEGORY, 
	PSNID_DESCRIPTION,
	PSNID_VALUE, 
	PSNID_EXPIRATION_DATE, 
	PSNID_ISSUER, 
	PSNID_ISSUE_DATE, 
	PSNID_LAST_VERIFICATION_DATE,
	PSNID_LAST_FM_DATE,
	DW_LOAD_DT
	)
	
	SELECT 
	stg.SERIAL,
	1,
	CURRENT_DATE,
	NULL,
	stg.SOURCEHASH2,
	stg.PARENT_SERIAL, 
	stg.ORDINAL, 
	stg.CATEGORY, 
	stg.DESCRIPTION, 
	stg.VALUE, 
	stg.EXPIRATION_DATE, 
	stg.ISSUER, 
	stg.ISSUE_DATE, 
	stg.LAST_VERIFICATION_DATE, 
	stg.LAST_FM_DATE,	
	CURRENT_DATE 
	FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_PERSON_ID_STG_CF stg
		WHERE ISNEW = 1 OR ISTYPE2 = 1;

END;
$$
;
