/*
--==================================================================================================
--Author: Farr, C
--Create Date:	2024-04-11  	
--Object Name:	sp_LOAD_T_CU_LOANPROMOCODE_STG
--Description:  Loading Loan Promo codes Data
--***********************************************************************************************************************
--Date			Trello#					ChangedBy						Description 
------------------------------------------------------------------------------------------------------------------------
*/


CREATE OR REPLACE PROCEDURE RRCU_STG_DEV.KEYSTONE_CORE.sp_LOAD_T_CU_LOANPROMOCODE_STG()
RETURNS VARCHAR NOT NULL
LANGUAGE SQL

AS
$$

BEGIN 
	
	TRUNCATE TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_CU_LOANPROMOCODE_STG_CF;
	
	-- REMOVE PK	
	ALTER TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_CU_LOANPROMOCODE_STG_CF DROP PRIMARY KEY;
	
	-- Populate STAGING WITH CTE DATA
	INSERT INTO RRCU_STG_DEV.KEYSTONE_CORE.T_KS_CU_LOANPROMOCODE_STG_CF
	(
	SERIAL,
	SOURCEHASH2,
	PARENT_SERIAL, 
	ORDINAL, 
	LAST_FM_DATE, 
	PROMOCODE
	)
	
	WITH CTE AS

	(	
	SELECT 
	SERIAL,
	MD5(TO_VARCHAR(ARRAY_CONSTRUCT(*))) AS SourceHash2,  -- SOURCE HASH	
	PARENT_SERIAL, 
	ORDINAL, 
	LAST_FM_DATE, 
	PROMOCODE,
	ROW_NUMBER() OVER (PARTITION BY SERIAL ORDER BY SERIAL) AS rn -- helps identify mutliple serial number dupes		
	FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_CU_LOANPROMOCODE_STG
	)

	SELECT SERIAL, SOURCEHASH2, PARENT_SERIAL, ORDINAL, LAST_FM_DATE, PROMOCODE,
	FROM CTE
	WHERE rn = 1;
	
-- DUPE CHECK / DELETE 
	DELETE FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_CU_LOANPROMOCODE_STG_CF USING (
    	WITH CTE_DUP AS
    	(
    	SELECT SERIAL,
	 	ROW_NUMBER () OVER ( PARTITION BY SERIAL ORDER BY SERIAL) AS RN
	 	FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_CU_LOANPROMOCODE_STG_CF
    	)
        SELECT SERIAL, RN FROM CTE_DUP
        ) AS CTE_RESULT
	WHERE CTE_RESULT.RN > 1;

	-- ADD PRIMARY KEY BACK

	ALTER TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_CU_LOANPROMOCODE_STG_CF ADD PRIMARY KEY (SERIAL);

	-- Expiration for records not coming back into resultset
	UPDATE RRCU_DW_DEV.DW.T_KS_CU_LOANPROMOCODE_DW_CF
	SET LNPC_CURR_IND = 0
	, LNPC_EXP_DT = CURRENT_DATE
	WHERE LNPC_CURR_IND = 1
	AND LNPC_SERIAL NOT IN (SELECT SERIAL FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_CU_LOANPROMOCODE_STG_CF);

	DROP TABLE IF EXISTS RRCU_STG_DEV.KEYSTONE_CORE.Update_STG;

	CREATE TEMPORARY TABLE RRCU_STG_DEV.KEYSTONE_CORE.Update_STG(
	LNPC_REC_KEY BIGINT,
	STG_SOURCEHASH2 VARCHAR(32),
	NEW_SOURCEHASH2 VARCHAR(32),
	IS_TYPE2 INT,  -- REPRESENTS TYPE 2
	IS_NEW INT -- INDICATION FOR NEW RECORD TYPE 2
	);


	INSERT INTO RRCU_STG_DEV.KEYSTONE_CORE.Update_STG (
	LNPC_REC_KEY,
	STG_SOURCEHASH2,
	NEW_SOURCEHASH2,
	IS_NEW,
	IS_TYPE2	
	)
	
	WITH CTE_COMPARE AS
	(
	SELECT dim.LNPC_REC_KEY ,  dim.LNPC_SOURCEHASH2, stg.sourcehash2,
	CASE WHEN dim.LNPC_REC_KEY IS NULL THEN 1 ELSE 0 END CASE,
	CASE WHEN dim.LNPC_REC_KEY IS NOT NULL AND stg.SOURCEHASH2 <> dim.LNPC_SOURCEHASH2 THEN 1 ELSE 0 END CASE
	FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_CU_LOANPROMOCODE_STG_CF stg
	LEFT OUTER JOIN RRCU_DW_DEV.DW.T_KS_CU_LOANPROMOCODE_DW_CF dim ON dim.LNPC_SERIAL = stg.SERIAL AND dim.LNPC_CURR_IND  = 1
	)
	SELECT *
	FROM CTE_COMPARE;
	
	UPDATE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_CU_LOANPROMOCODE_STG_CF a
	SET LNPC_REC_KEY = b.LNPC_REC_KEY,
	ISNEW = b.IS_NEW,
	ISTYPE2 = b.IS_TYPE2
	FROM (SELECT LNPC_REC_KEY, IS_NEW, IS_TYPE2, NEW_SOURCEHASH2 FROM RRCU_STG_DEV.KEYSTONE_CORE.Update_STG) b
	WHERE a.SOURCEHASH2 = b.NEW_SOURCEHASH2 AND a.LNPC_REC_KEY IS NULL;

	-- Expiration for records type 2
	
   UPDATE RRCU_DW_DEV.DW.T_KS_CU_LOANPROMOCODE_DW_CF
	SET LNPC_CURR_IND = 0
	, LNPC_EXP_DT = CURRENT_DATE
	WHERE LNPC_CURR_IND = 1
	AND LNPC_SERIAL IN (SELECT SERIAL FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_CU_LOANPROMOCODE_STG_CF WHERE ISTYPE2 = 1); 

	INSERT OVERWRITE INTO RRCU_DW_DEV.DW.T_KS_CU_LOANPROMOCODE_DW_CF
	(
	LNPC_SERIAL,
	LNPC_CURR_IND, 
	LNPC_EFF_DT, 
	LNPC_EXP_DT, 
	--LNPC_MOD_DT, 
	LNPC_SOURCEHASH2, 
	LNPC_PARENT_SERIAL, 
	LNPC_ORDINAL, 
	LNPC_LAST_FM_DATE, 
	LNPC_PROMOCODE, 
	DW_LOAD_DT
	)

	SELECT 
	stg.SERIAL,
	1,
	CURRENT_DATE,
	NULL,
	stg.SOURCEHASH2,
	stg.PARENT_SERIAL, 
	stg.ORDINAL, 
	stg.LAST_FM_DATE, 
	stg.PROMOCODE,
	CURRENT_DATE
	FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_CU_LOANPROMOCODE_STG_CF stg
		WHERE ISNEW = 1 OR ISTYPE2 = 1;


END;
$$
;

