--==================================================================================================
--Author: Farr, C
--Create Date:	2024-03-05  	
--Object Name:	sp_LOAD_T_ACCOUNT_CLOSE_REASON_STG
--Description:  Loading Account Eligibility Data
--***********************************************************************************************************************
--Date			Trello#					ChangedBy						Description 
------------------------------------------------------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE RRCU_STG_DEV.KEYSTONE_CORE.sp_LOAD_T_ACCOUNT_CLOSE_REASON_STG ()
RETURNS VARCHAR NOT NULL
LANGUAGE SQL

AS
$$

BEGIN 
	
	TRUNCATE TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_ACCOUNT_CLOSE_REASON_STG_CF;
	
	-- REMOVE PK	
	ALTER TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_ACCOUNT_CLOSE_REASON_STG_CF DROP PRIMARY KEY;
	
	-- Populate STAGING WITH CTE DATA
	INSERT INTO RRCU_STG_DEV.KEYSTONE_CORE.T_KS_ACCOUNT_CLOSE_REASON_STG_CF
	(
	SERIAL,
	SOURCEHASH2,
	LAST_FM_DATE,
	DESCRIPTION,
	STATUS,
	CODE
	)
	
	WITH CTE AS

	(	
	SELECT 
	SERIAL,
	MD5(TO_VARCHAR(ARRAY_CONSTRUCT(*))) AS SourceHash2,  -- SOURCE HASH	
	LAST_FM_DATE,
	DESCRIPTION,
	STATUS,
	CODE,
	ROW_NUMBER() OVER (PARTITION BY SERIAL ORDER BY SERIAL) AS rn -- helps identify mutliple serial number dupes		
	FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_ACCOUNT_CLOSE_REASON_STG
	)
	

	SELECT SERIAL, SOURCEHASH2, LAST_FM_DATE, DESCRIPTION, STATUS, CODE
	FROM CTE
	WHERE rn = 1;
	

	-- DUPE CHECK / DELETE 
	DELETE FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_ACCOUNT_CLOSE_REASON_STG_CF USING (
    	WITH CTE_DUP AS
    	(
    	SELECT SERIAL,
	 	ROW_NUMBER () OVER ( PARTITION BY SERIAL ORDER BY SERIAL) AS RN
	 	FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_ACCOUNT_CLOSE_REASON_STG_CF
    	)
        SELECT SERIAL, RN FROM CTE_DUP
        ) AS CTE_RESULT
	WHERE CTE_RESULT.RN > 1;

	-- ADD PRIMARY KEY BACK

	ALTER TABLE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_ACCOUNT_CLOSE_REASON_STG_CF ADD PRIMARY KEY (SERIAL);

	-- Expiration for records not coming back into resultset
	UPDATE RRCU_DW_DEV.DW.T_KS_ACCOUNT_CLOSE_REASON_DW_CF
	SET CLRSN_CURR_IND = 0
	, CLRSN_EXP_DT = CURRENT_DATE
	WHERE CLRSN_CURR_IND = 1
	AND CLRSN_SERIAL NOT IN (SELECT SERIAL FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_ACCOUNT_CLOSE_REASON_STG_CF);

	
	DROP TABLE IF EXISTS RRCU_STG_DEV.KEYSTONE_CORE.Update_STG;

	CREATE TEMPORARY TABLE RRCU_STG_DEV.KEYSTONE_CORE.Update_STG(
	CLRSN_REC_KEY BIGINT,
	STG_SOURCEHASH2 VARCHAR(32),
	NEW_SOURCEHASH2 VARCHAR(32),
	IS_TYPE2 INT,  -- REPRESENTS TYPE 2
	IS_NEW INT -- INDICATION FOR NEW RECORD TYPE 2
	);

	--DROP TABLE RRCU_STG_DEV.KEYSTONE_CORE.Update_STG;
	
	INSERT INTO RRCU_STG_DEV.KEYSTONE_CORE.Update_STG (
	CLRSN_REC_KEY,
	STG_SOURCEHASH2,
	NEW_SOURCEHASH2,
	IS_NEW,
	IS_TYPE2	
	)
	
	WITH CTE_COMPARE AS
	(
	SELECT dim.CLRSN_REC_KEY ,  dim.CLRSN_SOURCEHASH2, stg.sourcehash2,
	CASE WHEN dim.CLRSN_REC_KEY IS NULL THEN 1 ELSE 0 END CASE,
	CASE WHEN dim.CLRSN_REC_KEY IS NOT NULL AND stg.SOURCEHASH2 <> dim.CLRSN_SOURCEHASH2 THEN 1 ELSE 0 END CASE
	FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_ACCOUNT_CLOSE_REASON_STG_CF stg
	LEFT OUTER JOIN RRCU_DW_DEV.DW.T_KS_ACCOUNT_CLOSE_REASON_DW_CF dim ON dim.CLRSN_SERIAL = stg.SERIAL AND dim.CLRSN_CURR_IND  = 1
	)
	SELECT *
	FROM CTE_COMPARE;

	--SELECT * FROM RRCU_STG_DEV.KEYSTONE_CORE.Update_STG;
	--SELECT * FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_ACCOUNT_CLOSE_REASON_STG_CF;

	UPDATE RRCU_STG_DEV.KEYSTONE_CORE.T_KS_ACCOUNT_CLOSE_REASON_STG_CF a
	SET CLRSN_REC_KEY = b.CLRSN_REC_KEY,
	ISNEW = b.IS_NEW,
	ISTYPE2 = b.IS_TYPE2
	FROM (SELECT CLRSN_REC_KEY, IS_NEW, IS_TYPE2, NEW_SOURCEHASH2 FROM RRCU_STG_DEV.KEYSTONE_CORE.Update_STG) b
	WHERE a.SOURCEHASH2 = b.NEW_SOURCEHASH2 AND a.CLRSN_REC_KEY IS NULL;

	--SELECT isnew, count(*)
	--FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_ACCOUNT_CLOSE_REASON_STG_CF
	--WHERE isnew = 1
	--GROUP BY isnew
	--WHERE SOURCEHASH2 IN (SELECT NEW_SOURCEHASH2 FROM RRCU_STG_DEV.KEYSTONE_CORE.Update_STG);
	
   -- Expiration for records type 2
	
    UPDATE RRCU_DW_DEV.DW.T_KS_ACCOUNT_CLOSE_REASON_DW_CF
	SET CLRSN_CURR_IND = 0
	, CLRSN_EXP_DT = CURRENT_DATE
	WHERE CLRSN_CURR_IND = 1
	AND CLRSN_SERIAL IN (SELECT SERIAL FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_ACCOUNT_CLOSE_REASON_STG_CF WHERE ISTYPE2 = 1); 

	INSERT INTO RRCU_DW_DEV.DW.T_KS_ACCOUNT_CLOSE_REASON_DW_CF
	(
	CLRSN_SERIAL,
	CLRSN_CURR_IND,
	CLRSN_EFF_DT,
	CLRSN_EXP_DT,
	--CLRSN_MOD_DT,
	CLRSN_SOURCEHASH2,
	CLRSN_LAST_FM_DATE,
	CLRSN_DESCRIPTION,
	CLRSN_STATUS,
	CLRSN_CODE
	)
	
	SELECT 
	stg.SERIAL,
	1,
	CURRENT_DATE,
	NULL,
	stg.SOURCEHASH2,
 	stg.LAST_FM_DATE,
 	stg.DESCRIPTION,
 	stg.STATUS,
 	stg.CODE	

	FROM RRCU_STG_DEV.KEYSTONE_CORE.T_KS_ACCOUNT_CLOSE_REASON_STG_CF stg
		WHERE ISNEW = 1 OR ISTYPE2 = 1;
	

END;
$$
;